# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'box.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Box_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1016, 384)
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab)
        self.groupBox_11.setEnabled(True)
        self.groupBox_11.setTitle(_fromUtf8(""))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.leftlight2open = QtGui.QPushButton(self.groupBox_11)
        self.leftlight2open.setCheckable(True)
        self.leftlight2open.setObjectName(_fromUtf8("leftlight2open"))
        self.gridLayout_16.addWidget(self.leftlight2open, 1, 3, 1, 1)
        self.rightlight2non = QtGui.QPushButton(self.groupBox_11)
        self.rightlight2non.setCheckable(True)
        self.rightlight2non.setChecked(True)
        self.rightlight2non.setObjectName(_fromUtf8("rightlight2non"))
        self.gridLayout_16.addWidget(self.rightlight2non, 3, 1, 1, 1)
        self.rightlight2open = QtGui.QPushButton(self.groupBox_11)
        self.rightlight2open.setCheckable(True)
        self.rightlight2open.setObjectName(_fromUtf8("rightlight2open"))
        self.gridLayout_16.addWidget(self.rightlight2open, 3, 3, 1, 1)
        self.rightlight1close = QtGui.QPushButton(self.groupBox_11)
        self.rightlight1close.setCheckable(True)
        self.rightlight1close.setChecked(False)
        self.rightlight1close.setObjectName(_fromUtf8("rightlight1close"))
        self.gridLayout_16.addWidget(self.rightlight1close, 2, 4, 1, 1)
        self.leftlight1close = QtGui.QPushButton(self.groupBox_11)
        self.leftlight1close.setCheckable(True)
        self.leftlight1close.setChecked(False)
        self.leftlight1close.setObjectName(_fromUtf8("leftlight1close"))
        self.gridLayout_16.addWidget(self.leftlight1close, 0, 4, 1, 1)
        self.leftlight2non = QtGui.QPushButton(self.groupBox_11)
        self.leftlight2non.setCheckable(True)
        self.leftlight2non.setChecked(True)
        self.leftlight2non.setObjectName(_fromUtf8("leftlight2non"))
        self.gridLayout_16.addWidget(self.leftlight2non, 1, 1, 1, 1)
        self.leftlight1open = QtGui.QPushButton(self.groupBox_11)
        self.leftlight1open.setCheckable(True)
        self.leftlight1open.setObjectName(_fromUtf8("leftlight1open"))
        self.gridLayout_16.addWidget(self.leftlight1open, 0, 3, 1, 1)
        self.label_75 = QtGui.QLabel(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_75.sizePolicy().hasHeightForWidth())
        self.label_75.setSizePolicy(sizePolicy)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_16.addWidget(self.label_75, 4, 0, 1, 1)
        self.upboxnon = QtGui.QPushButton(self.groupBox_11)
        self.upboxnon.setCheckable(True)
        self.upboxnon.setChecked(True)
        self.upboxnon.setObjectName(_fromUtf8("upboxnon"))
        self.gridLayout_16.addWidget(self.upboxnon, 4, 1, 1, 1)
        self.label_54 = QtGui.QLabel(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_16.addWidget(self.label_54, 3, 0, 1, 1)
        self.label_51 = QtGui.QLabel(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_16.addWidget(self.label_51, 0, 0, 1, 1)
        self.upboxopen = QtGui.QPushButton(self.groupBox_11)
        self.upboxopen.setCheckable(True)
        self.upboxopen.setObjectName(_fromUtf8("upboxopen"))
        self.gridLayout_16.addWidget(self.upboxopen, 4, 3, 1, 1)
        self.rightlight1open = QtGui.QPushButton(self.groupBox_11)
        self.rightlight1open.setCheckable(True)
        self.rightlight1open.setObjectName(_fromUtf8("rightlight1open"))
        self.gridLayout_16.addWidget(self.rightlight1open, 2, 3, 1, 1)
        self.upboxclose = QtGui.QPushButton(self.groupBox_11)
        self.upboxclose.setCheckable(True)
        self.upboxclose.setChecked(False)
        self.upboxclose.setObjectName(_fromUtf8("upboxclose"))
        self.gridLayout_16.addWidget(self.upboxclose, 4, 4, 1, 1)
        self.rightlight1non = QtGui.QPushButton(self.groupBox_11)
        self.rightlight1non.setCheckable(True)
        self.rightlight1non.setChecked(True)
        self.rightlight1non.setObjectName(_fromUtf8("rightlight1non"))
        self.gridLayout_16.addWidget(self.rightlight1non, 2, 1, 1, 1)
        self.label_55 = QtGui.QLabel(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_16.addWidget(self.label_55, 2, 0, 1, 1)
        self.rightlight2close = QtGui.QPushButton(self.groupBox_11)
        self.rightlight2close.setCheckable(True)
        self.rightlight2close.setChecked(False)
        self.rightlight2close.setObjectName(_fromUtf8("rightlight2close"))
        self.gridLayout_16.addWidget(self.rightlight2close, 3, 4, 1, 1)
        self.label_53 = QtGui.QLabel(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_16.addWidget(self.label_53, 1, 0, 1, 1)
        self.leftlight2close = QtGui.QPushButton(self.groupBox_11)
        self.leftlight2close.setCheckable(True)
        self.leftlight2close.setChecked(False)
        self.leftlight2close.setObjectName(_fromUtf8("leftlight2close"))
        self.gridLayout_16.addWidget(self.leftlight2close, 1, 4, 1, 1)
        self.leftlight1non = QtGui.QPushButton(self.groupBox_11)
        self.leftlight1non.setCheckable(True)
        self.leftlight1non.setChecked(True)
        self.leftlight1non.setObjectName(_fromUtf8("leftlight1non"))
        self.gridLayout_16.addWidget(self.leftlight1non, 0, 1, 1, 1)
        self.downboxclose = QtGui.QPushButton(self.groupBox_11)
        self.downboxclose.setCheckable(True)
        self.downboxclose.setChecked(False)
        self.downboxclose.setObjectName(_fromUtf8("downboxclose"))
        self.gridLayout_16.addWidget(self.downboxclose, 5, 4, 1, 1)
        self.downboxnon = QtGui.QPushButton(self.groupBox_11)
        self.downboxnon.setCheckable(True)
        self.downboxnon.setChecked(True)
        self.downboxnon.setObjectName(_fromUtf8("downboxnon"))
        self.gridLayout_16.addWidget(self.downboxnon, 5, 1, 1, 1)
        self.downboxopen = QtGui.QPushButton(self.groupBox_11)
        self.downboxopen.setCheckable(True)
        self.downboxopen.setObjectName(_fromUtf8("downboxopen"))
        self.gridLayout_16.addWidget(self.downboxopen, 5, 3, 1, 1)
        self.label_76 = QtGui.QLabel(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_76.sizePolicy().hasHeightForWidth())
        self.label_76.setSizePolicy(sizePolicy)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_16.addWidget(self.label_76, 5, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_11, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_18 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.groupBox_12 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_12.setEnabled(True)
        self.groupBox_12.setTitle(_fromUtf8(""))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_78 = QtGui.QLabel(self.groupBox_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_78.sizePolicy().hasHeightForWidth())
        self.label_78.setSizePolicy(sizePolicy)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout_17.addWidget(self.label_78, 4, 0, 1, 1)
        self.downdoornon = QtGui.QPushButton(self.groupBox_12)
        self.downdoornon.setCheckable(True)
        self.downdoornon.setChecked(True)
        self.downdoornon.setObjectName(_fromUtf8("downdoornon"))
        self.gridLayout_17.addWidget(self.downdoornon, 4, 1, 1, 1)
        self.downdoorclose = QtGui.QPushButton(self.groupBox_12)
        self.downdoorclose.setCheckable(True)
        self.downdoorclose.setObjectName(_fromUtf8("downdoorclose"))
        self.gridLayout_17.addWidget(self.downdoorclose, 4, 4, 1, 1)
        self.downdooropen = QtGui.QPushButton(self.groupBox_12)
        self.downdooropen.setCheckable(True)
        self.downdooropen.setObjectName(_fromUtf8("downdooropen"))
        self.gridLayout_17.addWidget(self.downdooropen, 4, 3, 1, 1)
        self.updoorclose = QtGui.QPushButton(self.groupBox_12)
        self.updoorclose.setCheckable(True)
        self.updoorclose.setObjectName(_fromUtf8("updoorclose"))
        self.gridLayout_17.addWidget(self.updoorclose, 0, 4, 1, 1)
        self.updooropen = QtGui.QPushButton(self.groupBox_12)
        self.updooropen.setCheckable(True)
        self.updooropen.setObjectName(_fromUtf8("updooropen"))
        self.gridLayout_17.addWidget(self.updooropen, 0, 3, 1, 1)
        self.updoornon = QtGui.QPushButton(self.groupBox_12)
        self.updoornon.setCheckable(True)
        self.updoornon.setChecked(True)
        self.updoornon.setObjectName(_fromUtf8("updoornon"))
        self.gridLayout_17.addWidget(self.updoornon, 0, 1, 1, 1)
        self.label_77 = QtGui.QLabel(self.groupBox_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_77.sizePolicy().hasHeightForWidth())
        self.label_77.setSizePolicy(sizePolicy)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout_17.addWidget(self.label_77, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_12, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.tabWidget, 4, 2, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(Dialog)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_38 = QtGui.QLabel(self.groupBox_8)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_8.addWidget(self.label_38, 1, 4, 1, 1)
        self.comboBox = QtGui.QComboBox(self.groupBox_8)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.comboBox, 2, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.groupBox_8)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_8.addWidget(self.label_39, 1, 1, 1, 1)
        self.rightmotorvalue = QtGui.QSpinBox(self.groupBox_8)
        self.rightmotorvalue.setMaximum(2000)
        self.rightmotorvalue.setSingleStep(3)
        self.rightmotorvalue.setObjectName(_fromUtf8("rightmotorvalue"))
        self.gridLayout_8.addWidget(self.rightmotorvalue, 1, 5, 1, 1)
        self.leftmotorvalue = QtGui.QSpinBox(self.groupBox_8)
        self.leftmotorvalue.setMaximum(2000)
        self.leftmotorvalue.setSingleStep(3)
        self.leftmotorvalue.setObjectName(_fromUtf8("leftmotorvalue"))
        self.gridLayout_8.addWidget(self.leftmotorvalue, 1, 3, 1, 1)
        self.rightmotorcontrol = QtGui.QComboBox(self.groupBox_8)
        self.rightmotorcontrol.setObjectName(_fromUtf8("rightmotorcontrol"))
        self.rightmotorcontrol.addItem(_fromUtf8(""))
        self.rightmotorcontrol.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.rightmotorcontrol, 2, 5, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_8)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.comboBox_2, 2, 4, 1, 1)
        self.leftmotorcontrol = QtGui.QComboBox(self.groupBox_8)
        self.leftmotorcontrol.setObjectName(_fromUtf8("leftmotorcontrol"))
        self.leftmotorcontrol.addItem(_fromUtf8(""))
        self.leftmotorcontrol.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.leftmotorcontrol, 2, 3, 1, 1)
        self.loop = QtGui.QPushButton(self.groupBox_8)
        self.loop.setObjectName(_fromUtf8("loop"))
        self.gridLayout_8.addWidget(self.loop, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_8, 4, 1, 1, 1)
        self.tabWidget_2 = QtGui.QTabWidget(Dialog)
        self.tabWidget_2.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_58 = QtGui.QLabel(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_15.addWidget(self.label_58, 5, 2, 1, 1)
        self.label_42 = QtGui.QLabel(self.tab_5)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_15.addWidget(self.label_42, 0, 0, 1, 1)
        self.open = QtGui.QPushButton(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open.sizePolicy().hasHeightForWidth())
        self.open.setSizePolicy(sizePolicy)
        self.open.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.open.setObjectName(_fromUtf8("open"))
        self.gridLayout_15.addWidget(self.open, 0, 4, 1, 1)
        self.sernum = QtGui.QComboBox(self.tab_5)
        self.sernum.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sernum.sizePolicy().hasHeightForWidth())
        self.sernum.setSizePolicy(sizePolicy)
        self.sernum.setEditable(True)
        self.sernum.setObjectName(_fromUtf8("sernum"))
        self.gridLayout_15.addWidget(self.sernum, 0, 1, 1, 3)
        self.boundrate = QtGui.QComboBox(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boundrate.sizePolicy().hasHeightForWidth())
        self.boundrate.setSizePolicy(sizePolicy)
        self.boundrate.setEditable(True)
        self.boundrate.setObjectName(_fromUtf8("boundrate"))
        self.boundrate.addItem(_fromUtf8(""))
        self.boundrate.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.boundrate, 1, 1, 1, 3)
        self.close = QtGui.QPushButton(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close.sizePolicy().hasHeightForWidth())
        self.close.setSizePolicy(sizePolicy)
        self.close.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.close.setObjectName(_fromUtf8("close"))
        self.gridLayout_15.addWidget(self.close, 1, 4, 1, 1)
        self.titopause = QtGui.QPushButton(self.tab_5)
        self.titopause.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titopause.sizePolicy().hasHeightForWidth())
        self.titopause.setSizePolicy(sizePolicy)
        self.titopause.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.titopause.setObjectName(_fromUtf8("titopause"))
        self.gridLayout_15.addWidget(self.titopause, 4, 4, 1, 1)
        self.label_43 = QtGui.QLabel(self.tab_5)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_15.addWidget(self.label_43, 1, 0, 1, 1)
        self.runstat = QtGui.QLabel(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runstat.sizePolicy().hasHeightForWidth())
        self.runstat.setSizePolicy(sizePolicy)
        self.runstat.setObjectName(_fromUtf8("runstat"))
        self.gridLayout_15.addWidget(self.runstat, 5, 4, 1, 1)
        self.titostart = QtGui.QPushButton(self.tab_5)
        self.titostart.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titostart.sizePolicy().hasHeightForWidth())
        self.titostart.setSizePolicy(sizePolicy)
        self.titostart.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.titostart.setObjectName(_fromUtf8("titostart"))
        self.gridLayout_15.addWidget(self.titostart, 4, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.tab_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_15.addWidget(self.label_2, 6, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem, 6, 0, 1, 1)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.tab_5)
        self.lcdNumber_2.setDigitCount(8)
        self.lcdNumber_2.setProperty("value", 0.0)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.gridLayout_15.addWidget(self.lcdNumber_2, 6, 2, 1, 3)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.tabWidget_2, 4, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(Dialog)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_63 = QtGui.QLabel(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_13.addWidget(self.label_63, 0, 0, 1, 1)
        self.leftswitch1 = QtGui.QTextBrowser(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftswitch1.sizePolicy().hasHeightForWidth())
        self.leftswitch1.setSizePolicy(sizePolicy)
        self.leftswitch1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.leftswitch1.setObjectName(_fromUtf8("leftswitch1"))
        self.gridLayout_13.addWidget(self.leftswitch1, 0, 1, 1, 1)
        self.leftswitch2 = QtGui.QTextBrowser(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftswitch2.sizePolicy().hasHeightForWidth())
        self.leftswitch2.setSizePolicy(sizePolicy)
        self.leftswitch2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.leftswitch2.setObjectName(_fromUtf8("leftswitch2"))
        self.gridLayout_13.addWidget(self.leftswitch2, 0, 3, 1, 1)
        self.label_62 = QtGui.QLabel(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_13.addWidget(self.label_62, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 255);"))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_31 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_5.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_5.addWidget(self.label_32, 0, 2, 1, 1)
        self.chargestat = QtGui.QTextBrowser(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chargestat.sizePolicy().hasHeightForWidth())
        self.chargestat.setSizePolicy(sizePolicy)
        self.chargestat.setMaximumSize(QtCore.QSize(16777215, 29))
        self.chargestat.setObjectName(_fromUtf8("chargestat"))
        self.gridLayout_5.addWidget(self.chargestat, 0, 1, 1, 1)
        self.soc = QtGui.QProgressBar(self.groupBox_5)
        self.soc.setMaximumSize(QtCore.QSize(16777215, 20))
        self.soc.setProperty("value", 0)
        self.soc.setObjectName(_fromUtf8("soc"))
        self.gridLayout_5.addWidget(self.soc, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 1, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lcdNumber = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.gridLayout.addWidget(self.lcdNumber, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lcdNumber_3 = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumber_3.setDigitCount(8)
        self.lcdNumber_3.setProperty("value", 0.0)
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.gridLayout.addWidget(self.lcdNumber_3, 3, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_9)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.leftlight2open.setText(_translate("Dialog", "打开", None))
        self.rightlight2non.setText(_translate("Dialog", "无动作", None))
        self.rightlight2open.setText(_translate("Dialog", "打开", None))
        self.rightlight1close.setText(_translate("Dialog", "关闭", None))
        self.leftlight1close.setText(_translate("Dialog", "关闭", None))
        self.leftlight2non.setText(_translate("Dialog", "无动作", None))
        self.leftlight1open.setText(_translate("Dialog", "打开", None))
        self.label_75.setText(_translate("Dialog", "上盒：", None))
        self.upboxnon.setText(_translate("Dialog", "无动作", None))
        self.label_54.setText(_translate("Dialog", "右舵机2号灯：", None))
        self.label_51.setText(_translate("Dialog", "左舵机1号灯：", None))
        self.upboxopen.setText(_translate("Dialog", "打开", None))
        self.rightlight1open.setText(_translate("Dialog", "打开", None))
        self.upboxclose.setText(_translate("Dialog", "关闭", None))
        self.rightlight1non.setText(_translate("Dialog", "无动作", None))
        self.label_55.setText(_translate("Dialog", "右舵机1号灯：", None))
        self.rightlight2close.setText(_translate("Dialog", "关闭", None))
        self.label_53.setText(_translate("Dialog", "左舵机2号灯：", None))
        self.leftlight2close.setText(_translate("Dialog", "关闭", None))
        self.leftlight1non.setText(_translate("Dialog", "无动作", None))
        self.downboxclose.setText(_translate("Dialog", "关闭", None))
        self.downboxnon.setText(_translate("Dialog", "无动作", None))
        self.downboxopen.setText(_translate("Dialog", "打开", None))
        self.label_76.setText(_translate("Dialog", "下盒：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "舵机控制", None))
        self.label_78.setText(_translate("Dialog", "下盒门：", None))
        self.downdoornon.setText(_translate("Dialog", "无动作", None))
        self.downdoorclose.setText(_translate("Dialog", "关闭", None))
        self.downdooropen.setText(_translate("Dialog", "打开", None))
        self.updoorclose.setText(_translate("Dialog", "关闭", None))
        self.updooropen.setText(_translate("Dialog", "打开", None))
        self.updoornon.setText(_translate("Dialog", "无动作", None))
        self.label_77.setText(_translate("Dialog", "上盒门：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "开门电机", None))
        self.groupBox_8.setTitle(_translate("Dialog", "电机控制", None))
        self.label_38.setText(_translate("Dialog", "右电机速度：", None))
        self.comboBox.setItemText(0, _translate("Dialog", "正向", None))
        self.comboBox.setItemText(1, _translate("Dialog", "反向", None))
        self.label_39.setText(_translate("Dialog", "左电机速度：", None))
        self.rightmotorcontrol.setItemText(0, _translate("Dialog", "使能", None))
        self.rightmotorcontrol.setItemText(1, _translate("Dialog", "释放", None))
        self.comboBox_2.setItemText(0, _translate("Dialog", "正向", None))
        self.comboBox_2.setItemText(1, _translate("Dialog", "反向", None))
        self.leftmotorcontrol.setItemText(0, _translate("Dialog", "使能", None))
        self.leftmotorcontrol.setItemText(1, _translate("Dialog", "释放", None))
        self.loop.setText(_translate("Dialog", "往返", None))
        self.label_58.setText(_translate("Dialog", "运行状态：", None))
        self.label_42.setText(_translate("Dialog", "端口号：", None))
        self.open.setText(_translate("Dialog", "打开", None))
        self.boundrate.setItemText(0, _translate("Dialog", "1000000", None))
        self.boundrate.setItemText(1, _translate("Dialog", "115200", None))
        self.close.setText(_translate("Dialog", "关闭", None))
        self.titopause.setText(_translate("Dialog", "暂停", None))
        self.label_43.setText(_translate("Dialog", "波特率：", None))
        self.runstat.setText(_translate("Dialog", "停止", None))
        self.titostart.setText(_translate("Dialog", "开始测试", None))
        self.label_2.setText(_translate("Dialog", " 超声3计数：", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Dialog", "串口设置", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Dialog", "测试控制", None))
        self.groupBox_9.setTitle(_translate("Dialog", "舵机驱动器信息", None))
        self.label_63.setText(_translate("Dialog", "左1限位：", None))
        self.label_62.setText(_translate("Dialog", "左2限位：", None))
        self.groupBox_5.setTitle(_translate("Dialog", "电池", None))
        self.label_31.setText(_translate("Dialog", "状态：", None))
        self.label_32.setText(_translate("Dialog", "电量：", None))
        self.label.setText(_translate("Dialog", " 测试计数：", None))
        self.label_3.setText(_translate("Dialog", " 错误计数：", None))

import image_rc
