# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dboard.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Dboard_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(966, 711)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 932, 682))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 1)
        self.failedcount = QtGui.QLabel(self.groupBox_5)
        self.failedcount.setObjectName(_fromUtf8("failedcount"))
        self.gridLayout_6.addWidget(self.failedcount, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_8.setTitle(_fromUtf8(""))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label = QtGui.QLabel(self.groupBox_8)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        self.testbar = QtGui.QProgressBar(self.groupBox_8)
        self.testbar.setProperty("value", 0)
        self.testbar.setObjectName(_fromUtf8("testbar"))
        self.gridLayout_9.addWidget(self.testbar, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_8, 2, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.clear = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        self.clear.setObjectName(_fromUtf8("clear"))
        self.gridLayout_4.addWidget(self.clear, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 1)
        self.testmessage = QtGui.QTextBrowser(self.groupBox)
        self.testmessage.setObjectName(_fromUtf8("testmessage"))
        self.gridLayout_4.addWidget(self.testmessage, 0, 0, 2, 3)
        self.gridLayout_5.addWidget(self.groupBox, 1, 2, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.testitem = QtGui.QListWidget(self.groupBox_6)
        self.testitem.setObjectName(_fromUtf8("testitem"))
        self.gridLayout_7.addWidget(self.testitem, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.reginfo = QtGui.QTextBrowser(self.groupBox_2)
        self.reginfo.setObjectName(_fromUtf8("reginfo"))
        self.gridLayout.addWidget(self.reginfo, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.groupBox_3)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_10.addWidget(self.label_2, 0, 0, 1, 1)
        self.serialnum = QtGui.QComboBox(self.tab)
        self.serialnum.setEditable(True)
        self.serialnum.setObjectName(_fromUtf8("serialnum"))
        self.gridLayout_10.addWidget(self.serialnum, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_10.addWidget(self.label_12, 1, 0, 1, 1)
        self.boundrate = QtGui.QComboBox(self.tab)
        self.boundrate.setEditable(True)
        self.boundrate.setObjectName(_fromUtf8("boundrate"))
        self.boundrate.addItem(_fromUtf8(""))
        self.boundrate.addItem(_fromUtf8(""))
        self.boundrate.addItem(_fromUtf8(""))
        self.boundrate.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.boundrate, 1, 1, 1, 1)
        self.serialset = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serialset.sizePolicy().hasHeightForWidth())
        self.serialset.setSizePolicy(sizePolicy)
        self.serialset.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.serialset.setObjectName(_fromUtf8("serialset"))
        self.gridLayout_10.addWidget(self.serialset, 2, 1, 1, 1)
        self.close = QtGui.QPushButton(self.tab)
        self.close.setEnabled(False)
        self.close.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.close.setObjectName(_fromUtf8("close"))
        self.gridLayout_10.addWidget(self.close, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.boardlist = QtGui.QListWidget(self.tab_2)
        self.boardlist.setEnabled(False)
        self.boardlist.setGeometry(QtCore.QRect(10, 10, 241, 211))
        self.boardlist.setObjectName(_fromUtf8("boardlist"))
        item = QtGui.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/set.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/wifi.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/montor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon2)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon3)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/firmware.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon4)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/battery.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/IR.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon6)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon6)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon6)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon6)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon6)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon6)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon6)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon6)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon6)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/chaoshen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon7)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon7)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon7)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon7)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon7)
        self.boardlist.addItem(item)
        item = QtGui.QListWidgetItem()
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/denguang.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon8)
        self.boardlist.addItem(item)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.otatable = QtGui.QWidget()
        self.otatable.setObjectName(_fromUtf8("otatable"))
        self.otalist = QtGui.QListWidget(self.otatable)
        self.otalist.setEnabled(False)
        self.otalist.setGeometry(QtCore.QRect(10, 10, 241, 211))
        self.otalist.setObjectName(_fromUtf8("otalist"))
        item = QtGui.QListWidgetItem()
        item.setIcon(icon)
        self.otalist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon1)
        self.otalist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon2)
        self.otalist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon3)
        self.otalist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon4)
        self.otalist.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setIcon(icon6)
        self.otalist.addItem(item)
        self.tabWidget.addTab(self.otatable, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.modelset = QtGui.QPushButton(self.tab_4)
        self.modelset.setEnabled(False)
        self.modelset.setGeometry(QtCore.QRect(150, 50, 75, 21))
        self.modelset.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.modelset.setObjectName(_fromUtf8("modelset"))
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 54, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(80, 50, 61, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.buslist = QtGui.QListWidget(self.tab_3)
        self.buslist.setEnabled(False)
        self.buslist.setGeometry(QtCore.QRect(10, 10, 241, 221))
        self.buslist.setObjectName(_fromUtf8("buslist"))
        item = QtGui.QListWidgetItem()
        self.buslist.addItem(item)
        item = QtGui.QListWidgetItem()
        self.buslist.addItem(item)
        item = QtGui.QListWidgetItem()
        self.buslist.addItem(item)
        item = QtGui.QListWidgetItem()
        self.buslist.addItem(item)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.tabWidget_2 = QtGui.QTabWidget(self.layoutWidget)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.testitem_2 = QtGui.QListWidget(self.tab_6)
        self.testitem_2.setObjectName(_fromUtf8("testitem_2"))
        self.gridLayout_11.addWidget(self.testitem_2, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_11.setEnabled(False)
        self.groupBox_11.setTitle(_fromUtf8(""))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_58 = QtGui.QLabel(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_8.addWidget(self.label_58, 0, 0, 1, 1)
        self.box1non = QtGui.QPushButton(self.groupBox_11)
        self.box1non.setCheckable(True)
        self.box1non.setChecked(True)
        self.box1non.setObjectName(_fromUtf8("box1non"))
        self.gridLayout_8.addWidget(self.box1non, 0, 1, 1, 1)
        self.box1open = QtGui.QPushButton(self.groupBox_11)
        self.box1open.setCheckable(True)
        self.box1open.setObjectName(_fromUtf8("box1open"))
        self.gridLayout_8.addWidget(self.box1open, 0, 2, 1, 1)
        self.box1close = QtGui.QPushButton(self.groupBox_11)
        self.box1close.setCheckable(True)
        self.box1close.setChecked(False)
        self.box1close.setObjectName(_fromUtf8("box1close"))
        self.gridLayout_8.addWidget(self.box1close, 0, 3, 1, 1)
        self.label_59 = QtGui.QLabel(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_8.addWidget(self.label_59, 1, 0, 1, 1)
        self.box2non = QtGui.QPushButton(self.groupBox_11)
        self.box2non.setCheckable(True)
        self.box2non.setChecked(True)
        self.box2non.setObjectName(_fromUtf8("box2non"))
        self.gridLayout_8.addWidget(self.box2non, 1, 1, 1, 1)
        self.box2open = QtGui.QPushButton(self.groupBox_11)
        self.box2open.setCheckable(True)
        self.box2open.setObjectName(_fromUtf8("box2open"))
        self.gridLayout_8.addWidget(self.box2open, 1, 2, 1, 1)
        self.box2close = QtGui.QPushButton(self.groupBox_11)
        self.box2close.setCheckable(True)
        self.box2close.setChecked(False)
        self.box2close.setObjectName(_fromUtf8("box2close"))
        self.gridLayout_8.addWidget(self.box2close, 1, 3, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_11, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget_2, 1, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 1)
        self.boardsn = QtGui.QTextEdit(self.groupBox_4)
        self.boardsn.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boardsn.sizePolicy().hasHeightForWidth())
        self.boardsn.setSizePolicy(sizePolicy)
        self.boardsn.setMaximumSize(QtCore.QSize(173, 36))
        self.boardsn.setObjectName(_fromUtf8("boardsn"))
        self.gridLayout_3.addWidget(self.boardsn, 0, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.protol = QtGui.QTextEdit(self.groupBox_4)
        self.protol.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.protol.sizePolicy().hasHeightForWidth())
        self.protol.setSizePolicy(sizePolicy)
        self.protol.setMaximumSize(QtCore.QSize(173, 36))
        self.protol.setObjectName(_fromUtf8("protol"))
        self.gridLayout_3.addWidget(self.protol, 4, 1, 1, 2)
        self.software = QtGui.QTextEdit(self.groupBox_4)
        self.software.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.software.sizePolicy().hasHeightForWidth())
        self.software.setSizePolicy(sizePolicy)
        self.software.setMaximumSize(QtCore.QSize(173, 35))
        self.software.setObjectName(_fromUtf8("software"))
        self.gridLayout_3.addWidget(self.software, 3, 1, 1, 2)
        self.hardware = QtGui.QTextEdit(self.groupBox_4)
        self.hardware.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hardware.sizePolicy().hasHeightForWidth())
        self.hardware.setSizePolicy(sizePolicy)
        self.hardware.setMaximumSize(QtCore.QSize(173, 35))
        self.hardware.setObjectName(_fromUtf8("hardware"))
        self.gridLayout_3.addWidget(self.hardware, 2, 1, 1, 2)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.BID = QtGui.QTextEdit(self.groupBox_4)
        self.BID.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BID.sizePolicy().hasHeightForWidth())
        self.BID.setSizePolicy(sizePolicy)
        self.BID.setMaximumSize(QtCore.QSize(173, 36))
        self.BID.setObjectName(_fromUtf8("BID"))
        self.gridLayout_3.addWidget(self.BID, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 5, 0, 1, 1)
        self.bootver = QtGui.QTextEdit(self.groupBox_4)
        self.bootver.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bootver.sizePolicy().hasHeightForWidth())
        self.bootver.setSizePolicy(sizePolicy)
        self.bootver.setMaximumSize(QtCore.QSize(173, 36))
        self.bootver.setObjectName(_fromUtf8("bootver"))
        self.gridLayout_3.addWidget(self.bootver, 5, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 0, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.boardlist.setCurrentRow(-1)
        self.otalist.setCurrentRow(-1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "YG协议单板D测试", None))
        self.groupBox_5.setTitle(_translate("Dialog", "结果统计", None))
        self.label_13.setText(_translate("Dialog", "失败次数：", None))
        self.failedcount.setText(_translate("Dialog", "0", None))
        self.label.setText(_translate("Dialog", "测试进度：", None))
        self.groupBox.setTitle(_translate("Dialog", "消息区", None))
        self.clear.setText(_translate("Dialog", "清除", None))
        self.groupBox_6.setTitle(_translate("Dialog", "测试项", None))
        self.groupBox_2.setTitle(_translate("Dialog", "单板寄存器信息-不可更改", None))
        self.groupBox_3.setTitle(_translate("Dialog", "设置", None))
        self.label_2.setText(_translate("Dialog", "串口号：", None))
        self.label_12.setText(_translate("Dialog", "波特率：", None))
        self.boundrate.setItemText(0, _translate("Dialog", "115200", None))
        self.boundrate.setItemText(1, _translate("Dialog", "1000000", None))
        self.boundrate.setItemText(2, _translate("Dialog", "9600", None))
        self.boundrate.setItemText(3, _translate("Dialog", "38400", None))
        self.serialset.setText(_translate("Dialog", "设置", None))
        self.close.setText(_translate("Dialog", "关闭", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "串口", None))
        self.boardlist.setToolTip(_translate("Dialog", "右键可设置为测试设备", None))
        __sortingEnabled = self.boardlist.isSortingEnabled()
        self.boardlist.setSortingEnabled(False)
        item = self.boardlist.item(0)
        item.setText(_translate("Dialog", "IMU", None))
        item = self.boardlist.item(1)
        item.setText(_translate("Dialog", "2.4G", None))
        item = self.boardlist.item(2)
        item.setText(_translate("Dialog", "左轮毂电机", None))
        item = self.boardlist.item(3)
        item.setText(_translate("Dialog", "右轮毂电机", None))
        item = self.boardlist.item(4)
        item.setText(_translate("Dialog", "直流电机驱动板1", None))
        item = self.boardlist.item(5)
        item.setText(_translate("Dialog", "直流电机驱动板2", None))
        item = self.boardlist.item(6)
        item.setText(_translate("Dialog", "左箱体控制板", None))
        item = self.boardlist.item(7)
        item.setText(_translate("Dialog", "右箱体控制板", None))
        item = self.boardlist.item(8)
        item.setText(_translate("Dialog", "BMS", None))
        item = self.boardlist.item(9)
        item.setText(_translate("Dialog", "红外1", None))
        item = self.boardlist.item(10)
        item.setText(_translate("Dialog", "红外2", None))
        item = self.boardlist.item(11)
        item.setText(_translate("Dialog", "红外3", None))
        item = self.boardlist.item(12)
        item.setText(_translate("Dialog", "红外4", None))
        item = self.boardlist.item(13)
        item.setText(_translate("Dialog", "红外5", None))
        item = self.boardlist.item(14)
        item.setText(_translate("Dialog", "红外6", None))
        item = self.boardlist.item(15)
        item.setText(_translate("Dialog", "红外7", None))
        item = self.boardlist.item(16)
        item.setText(_translate("Dialog", "红外8", None))
        item = self.boardlist.item(17)
        item.setText(_translate("Dialog", "红外9", None))
        item = self.boardlist.item(18)
        item.setText(_translate("Dialog", "红外10", None))
        item = self.boardlist.item(19)
        item.setText(_translate("Dialog", "超声D8", None))
        item = self.boardlist.item(20)
        item.setText(_translate("Dialog", "超声E8", None))
        item = self.boardlist.item(21)
        item.setText(_translate("Dialog", "超声F8", None))
        item = self.boardlist.item(22)
        item.setText(_translate("Dialog", "超声FA", None))
        item = self.boardlist.item(23)
        item.setText(_translate("Dialog", "超声FC", None))
        item = self.boardlist.item(24)
        item.setText(_translate("Dialog", "超声FE", None))
        item = self.boardlist.item(25)
        item.setText(_translate("Dialog", "灯光控制", None))
        self.boardlist.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "单板", None))
        self.otalist.setToolTip(_translate("Dialog", "右键可设置为测试设备", None))
        __sortingEnabled = self.otalist.isSortingEnabled()
        self.otalist.setSortingEnabled(False)
        item = self.otalist.item(0)
        item.setText(_translate("Dialog", "IMU", None))
        item = self.otalist.item(1)
        item.setText(_translate("Dialog", "2.4G", None))
        item = self.otalist.item(2)
        item.setText(_translate("Dialog", "轮毂电机", None))
        item = self.otalist.item(3)
        item.setText(_translate("Dialog", "开门电机", None))
        item = self.otalist.item(4)
        item.setText(_translate("Dialog", "左右箱体控制板", None))
        item = self.otalist.item(5)
        item.setText(_translate("Dialog", "红外传感器", None))
        self.otalist.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.otatable), _translate("Dialog", "OTA升级", None))
        self.modelset.setText(_translate("Dialog", "设定", None))
        self.label_4.setText(_translate("Dialog", "工作模式：", None))
        self.label_5.setText(_translate("Dialog", "转发模式", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "B板模式", None))
        __sortingEnabled = self.buslist.isSortingEnabled()
        self.buslist.setSortingEnabled(False)
        item = self.buslist.item(0)
        item.setText(_translate("Dialog", "BUS1", None))
        item = self.buslist.item(1)
        item.setText(_translate("Dialog", "BUS2", None))
        item = self.buslist.item(2)
        item.setText(_translate("Dialog", "BUS3", None))
        item = self.buslist.item(3)
        item.setText(_translate("Dialog", "BUS4", None))
        self.buslist.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "总线测试", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Dialog", "测试子项", None))
        self.label_58.setText(_translate("Dialog", "1号箱体：", None))
        self.box1non.setText(_translate("Dialog", "无动作", None))
        self.box1open.setText(_translate("Dialog", "打开", None))
        self.box1close.setText(_translate("Dialog", "关闭", None))
        self.label_59.setText(_translate("Dialog", "2号箱体：", None))
        self.box2non.setText(_translate("Dialog", "无动作", None))
        self.box2open.setText(_translate("Dialog", "打开", None))
        self.box2close.setText(_translate("Dialog", "关闭", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Dialog", "舵机控制", None))
        self.groupBox_4.setTitle(_translate("Dialog", "单板寄存器信息-可更改部分", None))
        self.label_8.setText(_translate("Dialog", "软件版本号：", None))
        self.label_7.setText(_translate("Dialog", "硬件版本号：", None))
        self.label_9.setText(_translate("Dialog", "协议版本号：", None))
        self.label_3.setText(_translate("Dialog", "SN：", None))
        self.label_10.setText(_translate("Dialog", "BID：", None))
        self.label_11.setText(_translate("Dialog", "boot版本号：", None))

import image_rc
