# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manual.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Manual_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(667, 672)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/set.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 341, 301))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.inittabWidget = QtGui.QTabWidget(self.groupBox)
        self.inittabWidget.setGeometry(QtCore.QRect(0, 20, 341, 281))
        self.inittabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.inittabWidget.setObjectName(_fromUtf8("inittabWidget"))
        self.initMaptab = QtGui.QWidget()
        self.initMaptab.setObjectName(_fromUtf8("initMaptab"))
        self.label = QtGui.QLabel(self.initMaptab)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.mapname = QtGui.QTextBrowser(self.initMaptab)
        self.mapname.setEnabled(False)
        self.mapname.setGeometry(QtCore.QRect(70, 10, 171, 31))
        self.mapname.setObjectName(_fromUtf8("mapname"))
        self.label_3 = QtGui.QLabel(self.initMaptab)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 51, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.mapnum = QtGui.QTextEdit(self.initMaptab)
        self.mapnum.setEnabled(False)
        self.mapnum.setGeometry(QtCore.QRect(70, 50, 89, 31))
        self.mapnum.setMaximumSize(QtCore.QSize(89, 31))
        self.mapnum.setObjectName(_fromUtf8("mapnum"))
        self.label_2 = QtGui.QLabel(self.initMaptab)
        self.label_2.setGeometry(QtCore.QRect(170, 50, 71, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.testplace = QtGui.QTextEdit(self.initMaptab)
        self.testplace.setGeometry(QtCore.QRect(240, 50, 89, 31))
        self.testplace.setMaximumSize(QtCore.QSize(89, 31))
        self.testplace.setObjectName(_fromUtf8("testplace"))
        self.place6 = QtGui.QTextEdit(self.initMaptab)
        self.place6.setGeometry(QtCore.QRect(240, 170, 89, 31))
        self.place6.setMaximumSize(QtCore.QSize(89, 31))
        self.place6.setObjectName(_fromUtf8("place6"))
        self.label_5 = QtGui.QLabel(self.initMaptab)
        self.label_5.setGeometry(QtCore.QRect(200, 90, 41, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.place4 = QtGui.QTextEdit(self.initMaptab)
        self.place4.setGeometry(QtCore.QRect(240, 130, 89, 31))
        self.place4.setMaximumSize(QtCore.QSize(89, 31))
        self.place4.setObjectName(_fromUtf8("place4"))
        self.label_7 = QtGui.QLabel(self.initMaptab)
        self.label_7.setGeometry(QtCore.QRect(200, 130, 41, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.initMaptab)
        self.label_9.setGeometry(QtCore.QRect(200, 170, 41, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.place2 = QtGui.QTextEdit(self.initMaptab)
        self.place2.setGeometry(QtCore.QRect(240, 90, 89, 31))
        self.place2.setMaximumSize(QtCore.QSize(89, 31))
        self.place2.setObjectName(_fromUtf8("place2"))
        self.updateini = QtGui.QPushButton(self.initMaptab)
        self.updateini.setGeometry(QtCore.QRect(10, 210, 51, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateini.sizePolicy().hasHeightForWidth())
        self.updateini.setSizePolicy(sizePolicy)
        self.updateini.setMinimumSize(QtCore.QSize(51, 23))
        self.updateini.setMaximumSize(QtCore.QSize(51, 23))
        self.updateini.setStyleSheet(_fromUtf8("background-color: rgb(255, 85, 255);"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateini.setIcon(icon1)
        self.updateini.setObjectName(_fromUtf8("updateini"))
        self.updatebar = QtGui.QProgressBar(self.initMaptab)
        self.updatebar.setEnabled(True)
        self.updatebar.setGeometry(QtCore.QRect(70, 210, 251, 20))
        self.updatebar.setProperty("value", 0)
        self.updatebar.setObjectName(_fromUtf8("updatebar"))
        self.label_8 = QtGui.QLabel(self.initMaptab)
        self.label_8.setGeometry(QtCore.QRect(30, 170, 42, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.place1 = QtGui.QTextEdit(self.initMaptab)
        self.place1.setGeometry(QtCore.QRect(70, 90, 89, 31))
        self.place1.setMaximumSize(QtCore.QSize(89, 31))
        self.place1.setObjectName(_fromUtf8("place1"))
        self.place5 = QtGui.QTextEdit(self.initMaptab)
        self.place5.setGeometry(QtCore.QRect(70, 170, 89, 31))
        self.place5.setMaximumSize(QtCore.QSize(89, 31))
        self.place5.setObjectName(_fromUtf8("place5"))
        self.label_4 = QtGui.QLabel(self.initMaptab)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 42, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(self.initMaptab)
        self.label_6.setGeometry(QtCore.QRect(30, 130, 42, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.place3 = QtGui.QTextEdit(self.initMaptab)
        self.place3.setGeometry(QtCore.QRect(70, 130, 89, 31))
        self.place3.setMaximumSize(QtCore.QSize(89, 31))
        self.place3.setObjectName(_fromUtf8("place3"))
        self.inittabWidget.addTab(self.initMaptab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.listWidget = QtGui.QListWidget(self.tab_2)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 321, 231))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.inittabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(360, 320, 291, 121))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.review = QtGui.QPushButton(self.groupBox_3)
        self.review.setGeometry(QtCore.QRect(10, 80, 76, 31))
        self.review.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.review.setIconSize(QtCore.QSize(16, 16))
        self.review.setAutoRepeat(False)
        self.review.setAutoExclusive(False)
        self.review.setDefault(False)
        self.review.setFlat(False)
        self.review.setObjectName(_fromUtf8("review"))
        self.softreset = QtGui.QPushButton(self.groupBox_3)
        self.softreset.setGeometry(QtCore.QRect(10, 20, 75, 31))
        self.softreset.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.softreset.setObjectName(_fromUtf8("softreset"))
        self.kill = QtGui.QPushButton(self.groupBox_3)
        self.kill.setGeometry(QtCore.QRect(190, 20, 81, 31))
        self.kill.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.kill.setObjectName(_fromUtf8("kill"))
        self.resetcore = QtGui.QPushButton(self.groupBox_3)
        self.resetcore.setGeometry(QtCore.QRect(100, 20, 81, 31))
        self.resetcore.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.resetcore.setObjectName(_fromUtf8("resetcore"))
        self.yogostat = QtGui.QPushButton(self.groupBox_3)
        self.yogostat.setGeometry(QtCore.QRect(100, 80, 81, 31))
        self.yogostat.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.yogostat.setObjectName(_fromUtf8("yogostat"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 320, 341, 331))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.textBrowser = QtGui.QTextBrowser(self.groupBox_4)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 321, 261))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.clear = QtGui.QPushButton(self.groupBox_4)
        self.clear.setGeometry(QtCore.QRect(260, 290, 71, 31))
        self.clear.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 255);"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear.setIcon(icon2)
        self.clear.setObjectName(_fromUtf8("clear"))
        self.logenable = QtGui.QPushButton(self.groupBox_4)
        self.logenable.setGeometry(QtCore.QRect(180, 290, 71, 31))
        self.logenable.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/log.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logenable.setIcon(icon3)
        self.logenable.setObjectName(_fromUtf8("logenable"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(10, 290, 81, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.netloger = QtGui.QLabel(self.groupBox_4)
        self.netloger.setGeometry(QtCore.QRect(90, 290, 31, 31))
        self.netloger.setObjectName(_fromUtf8("netloger"))
        self.constat = QtGui.QLabel(self.groupBox_4)
        self.constat.setGeometry(QtCore.QRect(130, 300, 31, 21))
        self.constat.setPixmap(QtGui.QPixmap(_fromUtf8("icons/green.png")))
        self.constat.setScaledContents(True)
        self.constat.setObjectName(_fromUtf8("constat"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 450, 291, 201))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.updatebar_2 = QtGui.QProgressBar(self.groupBox_2)
        self.updatebar_2.setGeometry(QtCore.QRect(100, 60, 181, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updatebar_2.sizePolicy().hasHeightForWidth())
        self.updatebar_2.setSizePolicy(sizePolicy)
        self.updatebar_2.setProperty("value", 0)
        self.updatebar_2.setObjectName(_fromUtf8("updatebar_2"))
        self.coreupload = QtGui.QPushButton(self.groupBox_2)
        self.coreupload.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.coreupload.setStyleSheet(_fromUtf8("background-color: rgb(255, 85, 255);"))
        self.coreupload.setIcon(icon1)
        self.coreupload.setObjectName(_fromUtf8("coreupload"))
        self.coreselect = QtGui.QPushButton(self.groupBox_2)
        self.coreselect.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.coreselect.setStyleSheet(_fromUtf8("background-color: rgb(255, 85, 255);"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/firmware.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.coreselect.setIcon(icon4)
        self.coreselect.setObjectName(_fromUtf8("coreselect"))
        self.corepath = QtGui.QTextBrowser(self.groupBox_2)
        self.corepath.setGeometry(QtCore.QRect(100, 30, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.corepath.setFont(font)
        self.corepath.setObjectName(_fromUtf8("corepath"))
        self.iniselet = QtGui.QPushButton(self.groupBox_2)
        self.iniselet.setGeometry(QtCore.QRect(10, 100, 81, 21))
        self.iniselet.setStyleSheet(_fromUtf8("background-color: rgb(255, 85, 255);"))
        self.iniselet.setObjectName(_fromUtf8("iniselet"))
        self.inipath = QtGui.QTextBrowser(self.groupBox_2)
        self.inipath.setGeometry(QtCore.QRect(100, 100, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.inipath.setFont(font)
        self.inipath.setObjectName(_fromUtf8("inipath"))
        self.inidown = QtGui.QPushButton(self.groupBox_2)
        self.inidown.setGeometry(QtCore.QRect(10, 130, 81, 21))
        self.inidown.setStyleSheet(_fromUtf8("background-color: rgb(255, 85, 255);"))
        self.inidown.setObjectName(_fromUtf8("inidown"))
        self.updatebar_3 = QtGui.QProgressBar(self.groupBox_2)
        self.updatebar_3.setGeometry(QtCore.QRect(100, 130, 181, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updatebar_3.sizePolicy().hasHeightForWidth())
        self.updatebar_3.setSizePolicy(sizePolicy)
        self.updatebar_3.setProperty("value", 0)
        self.updatebar_3.setObjectName(_fromUtf8("updatebar_3"))
        self.lable = QtGui.QLabel(self.groupBox_2)
        self.lable.setGeometry(QtCore.QRect(120, 170, 31, 21))
        self.lable.setText(_fromUtf8(""))
        self.lable.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/wifi.png")))
        self.lable.setScaledContents(True)
        self.lable.setObjectName(_fromUtf8("lable"))
        self.APSSID = QtGui.QLabel(self.groupBox_2)
        self.APSSID.setGeometry(QtCore.QRect(160, 170, 121, 21))
        self.APSSID.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.APSSID.setText(_fromUtf8(""))
        self.APSSID.setObjectName(_fromUtf8("APSSID"))
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(360, 10, 291, 301))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.mapselect = QtGui.QPushButton(self.groupBox_5)
        self.mapselect.setGeometry(QtCore.QRect(10, 270, 71, 21))
        self.mapselect.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.mapselect.setObjectName(_fromUtf8("mapselect"))
        self.mappatch = QtGui.QTextBrowser(self.groupBox_5)
        self.mappatch.setGeometry(QtCore.QRect(90, 270, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.mappatch.setFont(font)
        self.mappatch.setObjectName(_fromUtf8("mappatch"))
        self.maptablewidget = QtGui.QTabWidget(self.groupBox_5)
        self.maptablewidget.setGeometry(QtCore.QRect(0, 20, 291, 211))
        self.maptablewidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.maptablewidget.setStyleSheet(_fromUtf8(""))
        self.maptablewidget.setTabPosition(QtGui.QTabWidget.North)
        self.maptablewidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.maptablewidget.setObjectName(_fromUtf8("maptablewidget"))
        self.remotetable = QtGui.QWidget()
        self.remotetable.setObjectName(_fromUtf8("remotetable"))
        self.remotelist = QtGui.QListWidget(self.remotetable)
        self.remotelist.setGeometry(QtCore.QRect(10, 10, 271, 171))
        self.remotelist.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.remotelist.setObjectName(_fromUtf8("remotelist"))
        self.maptablewidget.addTab(self.remotetable, _fromUtf8(""))
        self.localtable = QtGui.QWidget()
        self.localtable.setObjectName(_fromUtf8("localtable"))
        self.localist = QtGui.QListWidget(self.localtable)
        self.localist.setGeometry(QtCore.QRect(10, 10, 271, 171))
        self.localist.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.localist.setObjectName(_fromUtf8("localist"))
        self.maptablewidget.addTab(self.localtable, _fromUtf8(""))
        self.maptable = QtGui.QWidget()
        self.maptable.setObjectName(_fromUtf8("maptable"))
        self.maplist = QtGui.QListWidget(self.maptable)
        self.maplist.setGeometry(QtCore.QRect(10, 10, 271, 171))
        self.maplist.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.maplist.setObjectName(_fromUtf8("maplist"))
        self.maptablewidget.addTab(self.maptable, _fromUtf8(""))
        self.mapreflush = QtGui.QPushButton(self.groupBox_5)
        self.mapreflush.setGeometry(QtCore.QRect(230, 240, 51, 23))
        self.mapreflush.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.mapreflush.setIcon(icon1)
        self.mapreflush.setObjectName(_fromUtf8("mapreflush"))

        self.retranslateUi(Dialog)
        self.inittabWidget.setCurrentIndex(0)
        self.maptablewidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "配置", None))
        self.groupBox.setTitle(_translate("Dialog", "远端ini配置", None))
        self.label.setText(_translate("Dialog", "Task Map：", None))
        self.label_3.setText(_translate("Dialog", "initMap：", None))
        self.label_2.setText(_translate("Dialog", "巡逻点数量：", None))
        self.label_5.setText(_translate("Dialog", "位置2：", None))
        self.label_7.setText(_translate("Dialog", "位置4：", None))
        self.label_9.setText(_translate("Dialog", "位置6：", None))
        self.updateini.setText(_translate("Dialog", "下载", None))
        self.label_8.setText(_translate("Dialog", "位置5：", None))
        self.place1.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_4.setText(_translate("Dialog", "位置1：", None))
        self.label_6.setText(_translate("Dialog", "位置3：", None))
        self.place3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.inittabWidget.setTabText(self.inittabWidget.indexOf(self.initMaptab), _translate("Dialog", "initMap配置", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", "开发中，敬请期待", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.inittabWidget.setTabText(self.inittabWidget.indexOf(self.tab_2), _translate("Dialog", "电梯配置", None))
        self.groupBox_3.setTitle(_translate("Dialog", "常用命令", None))
        self.review.setText(_translate("Dialog", "查看文件", None))
        self.softreset.setText(_translate("Dialog", "reboot", None))
        self.kill.setText(_translate("Dialog", "结束yogoCC", None))
        self.resetcore.setText(_translate("Dialog", "软启yogoCC", None))
        self.yogostat.setText(_translate("Dialog", "yogoCC状态", None))
        self.groupBox_4.setTitle(_translate("Dialog", "log", None))
        self.clear.setToolTip(_translate("Dialog", "清除所有面板信息", None))
        self.clear.setText(_translate("Dialog", "清除log", None))
        self.logenable.setToolTip(_translate("Dialog", "yogoCC输出log开关", None))
        self.logenable.setText(_translate("Dialog", "输出log", None))
        self.label_10.setText(_translate("Dialog", "PING失败次数：", None))
        self.netloger.setText(_translate("Dialog", "0", None))
        self.constat.setToolTip(_translate("Dialog", "网络状态指示", None))
        self.groupBox_2.setTitle(_translate("Dialog", "文件下载", None))
        self.coreupload.setText(_translate("Dialog", "下载", None))
        self.coreselect.setToolTip(_translate("Dialog", "点击可选择yogoCC", None))
        self.coreselect.setText(_translate("Dialog", "yogoCC", None))
        self.corepath.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.iniselet.setToolTip(_translate("Dialog", "可直接替换已配置好的ini文件", None))
        self.iniselet.setText(_translate("Dialog", "yogoCC.ini", None))
        self.inidown.setText(_translate("Dialog", "下载", None))
        self.groupBox_5.setTitle(_translate("Dialog", "地图配置-右键选中行可设置为initMap", None))
        self.mapselect.setToolTip(_translate("Dialog", "选择本地PC地图", None))
        self.mapselect.setText(_translate("Dialog", "新增地图", None))
        self.maptablewidget.setTabText(self.maptablewidget.indexOf(self.remotetable), _translate("Dialog", "远端地图", None))
        self.maptablewidget.setTabText(self.maptablewidget.indexOf(self.localtable), _translate("Dialog", "本地地图", None))
        self.maptablewidget.setTabText(self.maptablewidget.indexOf(self.maptable), _translate("Dialog", "地图映射", None))
        self.mapreflush.setText(_translate("Dialog", "刷新", None))

import image_rc
