# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'motor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Motor_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(742, 423)
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.groupBox_10 = QtGui.QGroupBox(Dialog)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.titomessage = QtGui.QTextBrowser(self.groupBox_10)
        self.titomessage.setObjectName(_fromUtf8("titomessage"))
        self.gridLayout_10.addWidget(self.titomessage, 0, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_10)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_10.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_10, 0, 2, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.test = QtGui.QPushButton(self.groupBox_2)
        self.test.setEnabled(True)
        self.test.setCheckable(True)
        self.test.setObjectName(_fromUtf8("test"))
        self.gridLayout_2.addWidget(self.test, 0, 1, 1, 1)
        self.stop = QtGui.QPushButton(self.groupBox_2)
        self.stop.setEnabled(True)
        self.stop.setCheckable(True)
        self.stop.setObjectName(_fromUtf8("stop"))
        self.gridLayout_2.addWidget(self.stop, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_2, 1, 2, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(Dialog)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_39 = QtGui.QLabel(self.groupBox_8)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_8.addWidget(self.label_39, 1, 0, 1, 1)
        self.leftmotorvalue = QtGui.QSpinBox(self.groupBox_8)
        self.leftmotorvalue.setEnabled(False)
        self.leftmotorvalue.setMaximum(2000)
        self.leftmotorvalue.setSingleStep(3)
        self.leftmotorvalue.setObjectName(_fromUtf8("leftmotorvalue"))
        self.gridLayout_8.addWidget(self.leftmotorvalue, 1, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_8)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_8.addWidget(self.label_40, 3, 0, 1, 1)
        self.leftstat = QtGui.QComboBox(self.groupBox_8)
        self.leftstat.setObjectName(_fromUtf8("leftstat"))
        self.leftstat.addItem(_fromUtf8(""))
        self.leftstat.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.leftstat, 4, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_8)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_8.addWidget(self.label, 4, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.groupBox_8)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.comboBox, 3, 1, 1, 1)
        self.leftmotordial = QtGui.QDial(self.groupBox_8)
        self.leftmotordial.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftmotordial.sizePolicy().hasHeightForWidth())
        self.leftmotordial.setSizePolicy(sizePolicy)
        self.leftmotordial.setMaximum(2000)
        self.leftmotordial.setSingleStep(3)
        self.leftmotordial.setWrapping(True)
        self.leftmotordial.setNotchTarget(3.0)
        self.leftmotordial.setNotchesVisible(True)
        self.leftmotordial.setObjectName(_fromUtf8("leftmotordial"))
        self.gridLayout_8.addWidget(self.leftmotordial, 0, 0, 1, 2)
        self.gridLayout_9.addWidget(self.groupBox_8, 0, 0, 2, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.rightmotordial = QtGui.QDial(self.groupBox)
        self.rightmotordial.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightmotordial.sizePolicy().hasHeightForWidth())
        self.rightmotordial.setSizePolicy(sizePolicy)
        self.rightmotordial.setMaximum(2000)
        self.rightmotordial.setSingleStep(3)
        self.rightmotordial.setWrapping(True)
        self.rightmotordial.setNotchTarget(3.0)
        self.rightmotordial.setNotchesVisible(True)
        self.rightmotordial.setObjectName(_fromUtf8("rightmotordial"))
        self.gridLayout.addWidget(self.rightmotordial, 0, 0, 1, 2)
        self.rightmotorvalue = QtGui.QSpinBox(self.groupBox)
        self.rightmotorvalue.setEnabled(False)
        self.rightmotorvalue.setMaximum(2000)
        self.rightmotorvalue.setSingleStep(3)
        self.rightmotorvalue.setObjectName(_fromUtf8("rightmotorvalue"))
        self.gridLayout.addWidget(self.rightmotorvalue, 1, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout.addWidget(self.label_38, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 2, 2)
        self.comboBox_2 = QtGui.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.rightstat = QtGui.QComboBox(self.groupBox)
        self.rightstat.setObjectName(_fromUtf8("rightstat"))
        self.rightstat.addItem(_fromUtf8(""))
        self.rightstat.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.rightstat, 4, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout.addWidget(self.label_41, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 0, 1, 2, 1)
        self.horizontalLayout.addLayout(self.gridLayout_9)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox_10.setTitle(_translate("Dialog", "消息区", None))
        self.pushButton_2.setText(_translate("Dialog", "清除", None))
        self.test.setText(_translate("Dialog", "开始", None))
        self.stop.setText(_translate("Dialog", "暂停", None))
        self.groupBox_8.setTitle(_translate("Dialog", "左电机控制", None))
        self.label_39.setText(_translate("Dialog", "左电机速度：", None))
        self.label_40.setText(_translate("Dialog", "方向：", None))
        self.leftstat.setItemText(0, _translate("Dialog", "使能", None))
        self.leftstat.setItemText(1, _translate("Dialog", "释放", None))
        self.label.setText(_translate("Dialog", "运行控制：", None))
        self.comboBox.setItemText(0, _translate("Dialog", "正向", None))
        self.comboBox.setItemText(1, _translate("Dialog", "反向", None))
        self.groupBox.setTitle(_translate("Dialog", "右电机控制", None))
        self.label_38.setText(_translate("Dialog", "右电机速度：", None))
        self.label_2.setText(_translate("Dialog", "运行控制：", None))
        self.comboBox_2.setItemText(0, _translate("Dialog", "正向", None))
        self.comboBox_2.setItemText(1, _translate("Dialog", "反向", None))
        self.rightstat.setItemText(0, _translate("Dialog", "使能", None))
        self.rightstat.setItemText(1, _translate("Dialog", "释放", None))
        self.label_41.setText(_translate("Dialog", "      方向：", None))

import image_rc
