# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ota.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Update_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(718, 656)
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.sublist = QtGui.QListWidget(self.groupBox_4)
        self.sublist.setEnabled(False)
        self.sublist.setObjectName(_fromUtf8("sublist"))
        self.gridLayout_5.addWidget(self.sublist, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setStyleSheet(_fromUtf8("color: rgb(0, 85, 255);"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.clear = QtGui.QPushButton(self.groupBox)
        self.clear.setObjectName(_fromUtf8("clear"))
        self.gridLayout.addWidget(self.clear, 1, 2, 1, 1)
        self.otamessage = QtGui.QTextBrowser(self.groupBox)
        self.otamessage.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.otamessage.setObjectName(_fromUtf8("otamessage"))
        self.gridLayout.addWidget(self.otamessage, 0, 0, 1, 3)
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setStyleSheet(_fromUtf8("color: rgb(85, 85, 255);"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verlist = QtGui.QListWidget(self.groupBox_2)
        self.verlist.setEnabled(False)
        self.verlist.setObjectName(_fromUtf8("verlist"))
        self.gridLayout_2.addWidget(self.verlist, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.upstat = QtGui.QLabel(self.groupBox_3)
        self.upstat.setObjectName(_fromUtf8("upstat"))
        self.gridLayout_3.addWidget(self.upstat, 1, 4, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 1, 3, 1, 1)
        self.upbar = QtGui.QProgressBar(self.groupBox_3)
        self.upbar.setMaximumSize(QtCore.QSize(201, 20))
        self.upbar.setProperty("value", 0)
        self.upbar.setObjectName(_fromUtf8("upbar"))
        self.gridLayout_3.addWidget(self.upbar, 3, 1, 1, 1)
        self.testloop = QtGui.QTextEdit(self.groupBox_3)
        self.testloop.setMaximumSize(QtCore.QSize(191, 31))
        self.testloop.setObjectName(_fromUtf8("testloop"))
        self.gridLayout_3.addWidget(self.testloop, 0, 1, 1, 1)
        self.textBrowser_3 = QtGui.QTextBrowser(self.groupBox_3)
        self.textBrowser_3.setMaximumSize(QtCore.QSize(191, 31))
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.gridLayout_3.addWidget(self.textBrowser_3, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 0);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 3, 3, 1, 1)
        self.firwareselect = QtGui.QPushButton(self.groupBox_3)
        self.firwareselect.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.firwareselect.setObjectName(_fromUtf8("firwareselect"))
        self.gridLayout_3.addWidget(self.firwareselect, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 3, 5, 1, 1)
        self.pause = QtGui.QPushButton(self.groupBox_3)
        self.pause.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.pause.setObjectName(_fromUtf8("pause"))
        self.gridLayout_3.addWidget(self.pause, 1, 5, 1, 1)
        self.successcount = QtGui.QLabel(self.groupBox_3)
        self.successcount.setObjectName(_fromUtf8("successcount"))
        self.gridLayout_3.addWidget(self.successcount, 3, 6, 1, 1)
        self.total = QtGui.QLabel(self.groupBox_3)
        self.total.setObjectName(_fromUtf8("total"))
        self.gridLayout_3.addWidget(self.total, 3, 4, 1, 1)
        self.errmd5 = QtGui.QCheckBox(self.groupBox_3)
        self.errmd5.setObjectName(_fromUtf8("errmd5"))
        self.gridLayout_3.addWidget(self.errmd5, 0, 3, 1, 1)
        self.errindex = QtGui.QCheckBox(self.groupBox_3)
        self.errindex.setObjectName(_fromUtf8("errindex"))
        self.gridLayout_3.addWidget(self.errindex, 0, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.errcrc = QtGui.QCheckBox(self.groupBox_3)
        self.errcrc.setObjectName(_fromUtf8("errcrc"))
        self.gridLayout_3.addWidget(self.errcrc, 0, 5, 1, 1)
        self.open = QtGui.QPushButton(self.groupBox_3)
        self.open.setEnabled(False)
        self.open.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.open.setObjectName(_fromUtf8("open"))
        self.gridLayout_3.addWidget(self.open, 1, 6, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 3, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_4)

        self.retranslateUi(Dialog)
        self.sublist.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "OTA升级界面", None))
        self.groupBox_4.setTitle(_translate("Dialog", "子设备选择", None))
        self.groupBox.setTitle(_translate("Dialog", "升级消息提示", None))
        self.clear.setText(_translate("Dialog", "清除消息", None))
        self.groupBox_2.setTitle(_translate("Dialog", "已有版本-双击可直接开始升级", None))
        self.upstat.setText(_translate("Dialog", "未开始", None))
        self.label.setText(_translate("Dialog", "升级状态：", None))
        self.label_2.setText(_translate("Dialog", "升级进度：", None))
        self.label_3.setText(_translate("Dialog", "升级次数：", None))
        self.firwareselect.setToolTip(_translate("Dialog", "可自由选择待升级固件", None))
        self.firwareselect.setText(_translate("Dialog", "新增固件", None))
        self.label_5.setText(_translate("Dialog", "成功次数：", None))
        self.pause.setToolTip(_translate("Dialog", "点击可打断升级过程，谨慎使用", None))
        self.pause.setText(_translate("Dialog", "结束升级", None))
        self.successcount.setText(_translate("Dialog", "0", None))
        self.total.setText(_translate("Dialog", "0", None))
        self.errmd5.setText(_translate("Dialog", "错误MD5", None))
        self.errindex.setText(_translate("Dialog", "Index重叠", None))
        self.label_4.setText(_translate("Dialog", "测试次数：", None))
        self.errcrc.setText(_translate("Dialog", "单帧CRC错误", None))
        self.open.setText(_translate("Dialog", "打开串口", None))

