# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uds.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Uds_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(927, 339)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(9, 9, 899, 311))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_9 = QtGui.QGridLayout(self.widget)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 255);"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.rightmotorpos = QtGui.QTextBrowser(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightmotorpos.sizePolicy().hasHeightForWidth())
        self.rightmotorpos.setSizePolicy(sizePolicy)
        self.rightmotorpos.setMaximumSize(QtCore.QSize(16777215, 26))
        self.rightmotorpos.setObjectName(_fromUtf8("rightmotorpos"))
        self.gridLayout.addWidget(self.rightmotorpos, 0, 3, 1, 1)
        self.leftmotorpos = QtGui.QTextBrowser(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftmotorpos.sizePolicy().hasHeightForWidth())
        self.leftmotorpos.setSizePolicy(sizePolicy)
        self.leftmotorpos.setMaximumSize(QtCore.QSize(16777215, 26))
        self.leftmotorpos.setObjectName(_fromUtf8("leftmotorpos"))
        self.gridLayout.addWidget(self.leftmotorpos, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.widget)
        self.groupBox_9.setStyleSheet(_fromUtf8("background-color: rgb(170, 85, 255);"))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_59 = QtGui.QLabel(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_13.addWidget(self.label_59, 0, 0, 1, 1)
        self.rightwei1 = QtGui.QTextBrowser(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightwei1.sizePolicy().hasHeightForWidth())
        self.rightwei1.setSizePolicy(sizePolicy)
        self.rightwei1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.rightwei1.setObjectName(_fromUtf8("rightwei1"))
        self.gridLayout_13.addWidget(self.rightwei1, 0, 3, 1, 1)
        self.label_66 = QtGui.QLabel(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_13.addWidget(self.label_66, 0, 2, 1, 1)
        self.leftwei1 = QtGui.QTextBrowser(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftwei1.sizePolicy().hasHeightForWidth())
        self.leftwei1.setSizePolicy(sizePolicy)
        self.leftwei1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.leftwei1.setObjectName(_fromUtf8("leftwei1"))
        self.gridLayout_13.addWidget(self.leftwei1, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_9, 0, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.widget)
        self.groupBox_6.setStyleSheet(_fromUtf8("background-color: rgb(149, 223, 0);"))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.errcode = QtGui.QTextBrowser(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errcode.sizePolicy().hasHeightForWidth())
        self.errcode.setSizePolicy(sizePolicy)
        self.errcode.setMaximumSize(QtCore.QSize(16777215, 27))
        self.errcode.setObjectName(_fromUtf8("errcode"))
        self.gridLayout_6.addWidget(self.errcode, 0, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_6.addWidget(self.label_33, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_6, 0, 2, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.widget)
        self.groupBox_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 0);"))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_44 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_4.addWidget(self.label_44, 2, 0, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_4.addWidget(self.label_47, 3, 2, 1, 1)
        self.irf8 = QtGui.QTextBrowser(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.irf8.sizePolicy().hasHeightForWidth())
        self.irf8.setSizePolicy(sizePolicy)
        self.irf8.setMaximumSize(QtCore.QSize(16777215, 26))
        self.irf8.setObjectName(_fromUtf8("irf8"))
        self.gridLayout_4.addWidget(self.irf8, 3, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 0, 0, 1, 1)
        self.irf2 = QtGui.QTextBrowser(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.irf2.sizePolicy().hasHeightForWidth())
        self.irf2.setSizePolicy(sizePolicy)
        self.irf2.setMaximumSize(QtCore.QSize(115, 27))
        self.irf2.setObjectName(_fromUtf8("irf2"))
        self.gridLayout_4.addWidget(self.irf2, 0, 3, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_4.addWidget(self.label_28, 0, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_4.addWidget(self.label_29, 1, 0, 1, 1)
        self.irf3 = QtGui.QTextBrowser(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.irf3.sizePolicy().hasHeightForWidth())
        self.irf3.setSizePolicy(sizePolicy)
        self.irf3.setMaximumSize(QtCore.QSize(16777215, 26))
        self.irf3.setObjectName(_fromUtf8("irf3"))
        self.gridLayout_4.addWidget(self.irf3, 1, 1, 1, 1)
        self.irf4 = QtGui.QTextBrowser(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.irf4.sizePolicy().hasHeightForWidth())
        self.irf4.setSizePolicy(sizePolicy)
        self.irf4.setMaximumSize(QtCore.QSize(16777215, 26))
        self.irf4.setObjectName(_fromUtf8("irf4"))
        self.gridLayout_4.addWidget(self.irf4, 1, 3, 1, 1)
        self.irf1 = QtGui.QTextBrowser(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.irf1.sizePolicy().hasHeightForWidth())
        self.irf1.setSizePolicy(sizePolicy)
        self.irf1.setMaximumSize(QtCore.QSize(16777215, 27))
        self.irf1.setObjectName(_fromUtf8("irf1"))
        self.gridLayout_4.addWidget(self.irf1, 0, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_4.addWidget(self.label_30, 1, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_4.addWidget(self.label_45, 2, 2, 1, 1)
        self.irf5 = QtGui.QTextBrowser(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.irf5.sizePolicy().hasHeightForWidth())
        self.irf5.setSizePolicy(sizePolicy)
        self.irf5.setMaximumSize(QtCore.QSize(16777215, 26))
        self.irf5.setObjectName(_fromUtf8("irf5"))
        self.gridLayout_4.addWidget(self.irf5, 2, 1, 1, 1)
        self.irf7 = QtGui.QTextBrowser(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.irf7.sizePolicy().hasHeightForWidth())
        self.irf7.setSizePolicy(sizePolicy)
        self.irf7.setMaximumSize(QtCore.QSize(16777215, 26))
        self.irf7.setObjectName(_fromUtf8("irf7"))
        self.gridLayout_4.addWidget(self.irf7, 3, 1, 1, 1)
        self.irf6 = QtGui.QTextBrowser(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.irf6.sizePolicy().hasHeightForWidth())
        self.irf6.setSizePolicy(sizePolicy)
        self.irf6.setMaximumSize(QtCore.QSize(16777215, 26))
        self.irf6.setObjectName(_fromUtf8("irf6"))
        self.gridLayout_4.addWidget(self.irf6, 2, 3, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_4.addWidget(self.label_46, 3, 0, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_4.addWidget(self.label_48, 4, 0, 1, 1)
        self.irf9 = QtGui.QTextBrowser(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.irf9.sizePolicy().hasHeightForWidth())
        self.irf9.setSizePolicy(sizePolicy)
        self.irf9.setMaximumSize(QtCore.QSize(16777215, 26))
        self.irf9.setObjectName(_fromUtf8("irf9"))
        self.gridLayout_4.addWidget(self.irf9, 4, 1, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_4.addWidget(self.label_49, 4, 2, 1, 1)
        self.irfA = QtGui.QTextBrowser(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.irfA.sizePolicy().hasHeightForWidth())
        self.irfA.setSizePolicy(sizePolicy)
        self.irfA.setMaximumSize(QtCore.QSize(16777215, 26))
        self.irfA.setObjectName(_fromUtf8("irfA"))
        self.gridLayout_4.addWidget(self.irfA, 4, 3, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_4, 1, 0, 2, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        self.groupBox_2.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 255);"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 1, 1)
        self.fuyang = QtGui.QTextBrowser(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fuyang.sizePolicy().hasHeightForWidth())
        self.fuyang.setSizePolicy(sizePolicy)
        self.fuyang.setMaximumSize(QtCore.QSize(16777215, 26))
        self.fuyang.setObjectName(_fromUtf8("fuyang"))
        self.gridLayout_2.addWidget(self.fuyang, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_2, 1, 2, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.widget)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_41 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_7.addWidget(self.label_41, 1, 0, 1, 1)
        self.leftdowndoor = QtGui.QTextBrowser(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftdowndoor.sizePolicy().hasHeightForWidth())
        self.leftdowndoor.setSizePolicy(sizePolicy)
        self.leftdowndoor.setMaximumSize(QtCore.QSize(16777215, 29))
        self.leftdowndoor.setObjectName(_fromUtf8("leftdowndoor"))
        self.gridLayout_7.addWidget(self.leftdowndoor, 1, 1, 1, 1)
        self.leftupdoor = QtGui.QTextBrowser(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftupdoor.sizePolicy().hasHeightForWidth())
        self.leftupdoor.setSizePolicy(sizePolicy)
        self.leftupdoor.setMaximumSize(QtCore.QSize(16777215, 29))
        self.leftupdoor.setObjectName(_fromUtf8("leftupdoor"))
        self.gridLayout_7.addWidget(self.leftupdoor, 0, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_7.addWidget(self.label_43, 1, 2, 1, 1)
        self.rightdowndoor = QtGui.QTextBrowser(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightdowndoor.sizePolicy().hasHeightForWidth())
        self.rightdowndoor.setSizePolicy(sizePolicy)
        self.rightdowndoor.setMaximumSize(QtCore.QSize(16777215, 29))
        self.rightdowndoor.setObjectName(_fromUtf8("rightdowndoor"))
        self.gridLayout_7.addWidget(self.rightdowndoor, 1, 3, 1, 1)
        self.label_42 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_7.addWidget(self.label_42, 0, 2, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_7.addWidget(self.label_40, 0, 0, 1, 1)
        self.rightupdoor = QtGui.QTextBrowser(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightupdoor.sizePolicy().hasHeightForWidth())
        self.rightupdoor.setSizePolicy(sizePolicy)
        self.rightupdoor.setMaximumSize(QtCore.QSize(16777215, 29))
        self.rightupdoor.setObjectName(_fromUtf8("rightupdoor"))
        self.gridLayout_7.addWidget(self.rightupdoor, 0, 3, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_7, 1, 1, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.widget)
        self.groupBox_5.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 255);"))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_31 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_5.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_5.addWidget(self.label_32, 0, 2, 1, 1)
        self.soc = QtGui.QProgressBar(self.groupBox_5)
        self.soc.setMaximumSize(QtCore.QSize(16777215, 20))
        self.soc.setProperty("value", 0)
        self.soc.setObjectName(_fromUtf8("soc"))
        self.gridLayout_5.addWidget(self.soc, 0, 3, 1, 1)
        self.chargestat = QtGui.QTextBrowser(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chargestat.sizePolicy().hasHeightForWidth())
        self.chargestat.setSizePolicy(sizePolicy)
        self.chargestat.setMaximumSize(QtCore.QSize(16777215, 29))
        self.chargestat.setObjectName(_fromUtf8("chargestat"))
        self.gridLayout_5.addWidget(self.chargestat, 0, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_5.addWidget(self.label_36, 1, 0, 1, 1)
        self.inch = QtGui.QTextBrowser(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inch.sizePolicy().hasHeightForWidth())
        self.inch.setSizePolicy(sizePolicy)
        self.inch.setMaximumSize(QtCore.QSize(16777215, 29))
        self.inch.setObjectName(_fromUtf8("inch"))
        self.gridLayout_5.addWidget(self.inch, 1, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_5.addWidget(self.label_37, 1, 2, 1, 1)
        self.fall = QtGui.QTextBrowser(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fall.sizePolicy().hasHeightForWidth())
        self.fall.setSizePolicy(sizePolicy)
        self.fall.setMaximumSize(QtCore.QSize(16777215, 29))
        self.fall.setObjectName(_fromUtf8("fall"))
        self.gridLayout_5.addWidget(self.fall, 1, 3, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 2, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.widget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.device = QtGui.QTextEdit(self.groupBox_3)
        self.device.setMaximumSize(QtCore.QSize(16777215, 31))
        self.device.setObjectName(_fromUtf8("device"))
        self.gridLayout_3.addWidget(self.device, 0, 1, 1, 1)
        self.start = QtGui.QPushButton(self.groupBox_3)
        self.start.setObjectName(_fromUtf8("start"))
        self.gridLayout_3.addWidget(self.start, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_3, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "轮毂电机驱动器", None))
        self.label.setText(_translate("Dialog", "左电机：", None))
        self.label_7.setText(_translate("Dialog", "右电机：", None))
        self.groupBox_9.setTitle(_translate("Dialog", "箱体控制板", None))
        self.label_59.setText(_translate("Dialog", "左箱体：", None))
        self.label_66.setText(_translate("Dialog", "右箱体：", None))
        self.groupBox_6.setTitle(_translate("Dialog", "C板", None))
        self.label_33.setText(_translate("Dialog", "故障码：", None))
        self.groupBox_4.setTitle(_translate("Dialog", "红外", None))
        self.label_44.setText(_translate("Dialog", "红外5：", None))
        self.label_47.setText(_translate("Dialog", "红外8：", None))
        self.label_27.setText(_translate("Dialog", "红外1：", None))
        self.label_28.setText(_translate("Dialog", "红外2：", None))
        self.label_29.setText(_translate("Dialog", "红外3：", None))
        self.label_30.setText(_translate("Dialog", "红外4：", None))
        self.label_45.setText(_translate("Dialog", "红外6：", None))
        self.label_46.setText(_translate("Dialog", "红外7：", None))
        self.label_48.setText(_translate("Dialog", "红外9：", None))
        self.label_49.setText(_translate("Dialog", "红外10：", None))
        self.groupBox_2.setTitle(_translate("Dialog", "IMU", None))
        self.label_16.setText(_translate("Dialog", "故障码：", None))
        self.groupBox_7.setTitle(_translate("Dialog", "开门电机", None))
        self.label_41.setText(_translate("Dialog", "左下门：", None))
        self.label_43.setText(_translate("Dialog", "右下门：", None))
        self.label_42.setText(_translate("Dialog", "右上门：", None))
        self.label_40.setText(_translate("Dialog", "左上门：", None))
        self.label_31.setText(_translate("Dialog", "电池状态：", None))
        self.label_32.setText(_translate("Dialog", "电量：", None))
        self.label_36.setText(_translate("Dialog", "碰撞环：", None))
        self.label_37.setText(_translate("Dialog", "跌落检测：", None))
        self.groupBox_3.setTitle(_translate("Dialog", "设置", None))
        self.start.setText(_translate("Dialog", "开始", None))
        self.label_2.setText(_translate("Dialog", "设备号：", None))

import image_rc
