# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1046, 640)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.boardStatus_4 = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boardStatus_4.sizePolicy().hasHeightForWidth())
        self.boardStatus_4.setSizePolicy(sizePolicy)
        self.boardStatus_4.setMaximumSize(QtCore.QSize(121, 31))
        self.boardStatus_4.setObjectName(_fromUtf8("boardStatus_4"))
        self.gridLayout.addWidget(self.boardStatus_4, 1, 7, 1, 1)
        self.groupBox_24 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_24.setObjectName(_fromUtf8("groupBox_24"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.groupBox_24)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.zitaijiaolable_4 = QtGui.QLabel(self.groupBox_24)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zitaijiaolable_4.sizePolicy().hasHeightForWidth())
        self.zitaijiaolable_4.setSizePolicy(sizePolicy)
        self.zitaijiaolable_4.setObjectName(_fromUtf8("zitaijiaolable_4"))
        self.verticalLayout_23.addWidget(self.zitaijiaolable_4)
        self.gridLayout.addWidget(self.groupBox_24, 1, 6, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.motorStatuslable = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motorStatuslable.sizePolicy().hasHeightForWidth())
        self.motorStatuslable.setSizePolicy(sizePolicy)
        self.motorStatuslable.setObjectName(_fromUtf8("motorStatuslable"))
        self.verticalLayout.addWidget(self.motorStatuslable)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_17 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_17.setTitle(_fromUtf8(""))
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_16.addWidget(self.label_17)
        self.gridLayout.addWidget(self.groupBox_17, 2, 2, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_9.setTitle(_fromUtf8(""))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_8.addWidget(self.label_9)
        self.gridLayout.addWidget(self.groupBox_9, 9, 2, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_6.addWidget(self.label_7)
        self.gridLayout.addWidget(self.groupBox_7, 8, 2, 1, 1)
        self.groupBox_21 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_21.setTitle(_fromUtf8(""))
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.groupBox_21)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.catchDelable = QtGui.QLabel(self.groupBox_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catchDelable.sizePolicy().hasHeightForWidth())
        self.catchDelable.setSizePolicy(sizePolicy)
        self.catchDelable.setObjectName(_fromUtf8("catchDelable"))
        self.verticalLayout_20.addWidget(self.catchDelable)
        self.gridLayout.addWidget(self.groupBox_21, 6, 0, 1, 1)
        self.downDelte = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downDelte.sizePolicy().hasHeightForWidth())
        self.downDelte.setSizePolicy(sizePolicy)
        self.downDelte.setMaximumSize(QtCore.QSize(121, 31))
        self.downDelte.setObjectName(_fromUtf8("downDelte"))
        self.gridLayout.addWidget(self.downDelte, 3, 1, 1, 1)
        self.groupBox_13 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_13.setTitle(_fromUtf8(""))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.sanzhoulable = QtGui.QLabel(self.groupBox_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sanzhoulable.sizePolicy().hasHeightForWidth())
        self.sanzhoulable.setSizePolicy(sizePolicy)
        self.sanzhoulable.setObjectName(_fromUtf8("sanzhoulable"))
        self.verticalLayout_12.addWidget(self.sanzhoulable)
        self.gridLayout.addWidget(self.groupBox_13, 0, 2, 1, 1)
        self.groupBox_20 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_20.setTitle(_fromUtf8(""))
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.groupBox_20)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_20)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_19.addWidget(self.label_20)
        self.gridLayout.addWidget(self.groupBox_20, 1, 2, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_8.setTitle(_fromUtf8(""))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.insideGatelable = QtGui.QLabel(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insideGatelable.sizePolicy().hasHeightForWidth())
        self.insideGatelable.setSizePolicy(sizePolicy)
        self.insideGatelable.setObjectName(_fromUtf8("insideGatelable"))
        self.verticalLayout_7.addWidget(self.insideGatelable)
        self.gridLayout.addWidget(self.groupBox_8, 5, 0, 1, 1)
        self.touchHead = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.touchHead.sizePolicy().hasHeightForWidth())
        self.touchHead.setSizePolicy(sizePolicy)
        self.touchHead.setMaximumSize(QtCore.QSize(121, 31))
        self.touchHead.setObjectName(_fromUtf8("touchHead"))
        self.gridLayout.addWidget(self.touchHead, 7, 1, 1, 1)
        self.insideGate = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insideGate.sizePolicy().hasHeightForWidth())
        self.insideGate.setSizePolicy(sizePolicy)
        self.insideGate.setMaximumSize(QtCore.QSize(121, 31))
        self.insideGate.setObjectName(_fromUtf8("insideGate"))
        self.gridLayout.addWidget(self.insideGate, 5, 1, 1, 1)
        self.chargeStatus = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chargeStatus.sizePolicy().hasHeightForWidth())
        self.chargeStatus.setSizePolicy(sizePolicy)
        self.chargeStatus.setMaximumSize(QtCore.QSize(121, 31))
        self.chargeStatus.setObjectName(_fromUtf8("chargeStatus"))
        self.gridLayout.addWidget(self.chargeStatus, 8, 1, 1, 1)
        self.dianti = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dianti.sizePolicy().hasHeightForWidth())
        self.dianti.setSizePolicy(sizePolicy)
        self.dianti.setMaximumSize(QtCore.QSize(121, 31))
        self.dianti.setObjectName(_fromUtf8("dianti"))
        self.gridLayout.addWidget(self.dianti, 2, 3, 1, 1)
        self.sanzhoucichang = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sanzhoucichang.sizePolicy().hasHeightForWidth())
        self.sanzhoucichang.setSizePolicy(sizePolicy)
        self.sanzhoucichang.setMaximumSize(QtCore.QSize(121, 31))
        self.sanzhoucichang.setObjectName(_fromUtf8("sanzhoucichang"))
        self.gridLayout.addWidget(self.sanzhoucichang, 0, 3, 1, 1)
        self.groupBox_11 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_11.setTitle(_fromUtf8(""))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.zitaijiaolable = QtGui.QLabel(self.groupBox_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zitaijiaolable.sizePolicy().hasHeightForWidth())
        self.zitaijiaolable.setSizePolicy(sizePolicy)
        self.zitaijiaolable.setObjectName(_fromUtf8("zitaijiaolable"))
        self.verticalLayout_10.addWidget(self.zitaijiaolable)
        self.gridLayout.addWidget(self.groupBox_11, 1, 0, 1, 1)
        self.catchDele = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catchDele.sizePolicy().hasHeightForWidth())
        self.catchDele.setSizePolicy(sizePolicy)
        self.catchDele.setMaximumSize(QtCore.QSize(121, 31))
        self.catchDele.setObjectName(_fromUtf8("catchDele"))
        self.gridLayout.addWidget(self.catchDele, 6, 1, 1, 1)
        self.groupBox_22 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_22.setTitle(_fromUtf8(""))
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.groupBox_22)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.label_22 = QtGui.QLabel(self.groupBox_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_21.addWidget(self.label_22)
        self.gridLayout.addWidget(self.groupBox_22, 7, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.boardlable = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boardlable.sizePolicy().hasHeightForWidth())
        self.boardlable.setSizePolicy(sizePolicy)
        self.boardlable.setObjectName(_fromUtf8("boardlable"))
        self.verticalLayout_2.addWidget(self.boardlable)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.zitaijiao = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zitaijiao.sizePolicy().hasHeightForWidth())
        self.zitaijiao.setSizePolicy(sizePolicy)
        self.zitaijiao.setMaximumSize(QtCore.QSize(121, 31))
        self.zitaijiao.setObjectName(_fromUtf8("zitaijiao"))
        self.gridLayout.addWidget(self.zitaijiao, 1, 1, 1, 1)
        self.xianwei = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xianwei.sizePolicy().hasHeightForWidth())
        self.xianwei.setSizePolicy(sizePolicy)
        self.xianwei.setMaximumSize(QtCore.QSize(121, 31))
        self.xianwei.setObjectName(_fromUtf8("xianwei"))
        self.gridLayout.addWidget(self.xianwei, 1, 3, 1, 1)
        self.boardStatus = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boardStatus.sizePolicy().hasHeightForWidth())
        self.boardStatus.setSizePolicy(sizePolicy)
        self.boardStatus.setMaximumSize(QtCore.QSize(121, 31))
        self.boardStatus.setObjectName(_fromUtf8("boardStatus"))
        self.gridLayout.addWidget(self.boardStatus, 0, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gateControlable = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gateControlable.sizePolicy().hasHeightForWidth())
        self.gateControlable.setSizePolicy(sizePolicy)
        self.gateControlable.setObjectName(_fromUtf8("gateControlable"))
        self.verticalLayout_5.addWidget(self.gateControlable)
        self.gridLayout.addWidget(self.groupBox_6, 4, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.gridLayout.addWidget(self.groupBox_4, 8, 0, 1, 1)
        self.groupBox_16 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_16.setTitle(_fromUtf8(""))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.downDeltelable = QtGui.QLabel(self.groupBox_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downDeltelable.sizePolicy().hasHeightForWidth())
        self.downDeltelable.setSizePolicy(sizePolicy)
        self.downDeltelable.setObjectName(_fromUtf8("downDeltelable"))
        self.verticalLayout_15.addWidget(self.downDeltelable)
        self.gridLayout.addWidget(self.groupBox_16, 3, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.gridLayout.addWidget(self.groupBox_5, 9, 0, 1, 1)
        self.motorStatus = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motorStatus.sizePolicy().hasHeightForWidth())
        self.motorStatus.setSizePolicy(sizePolicy)
        self.motorStatus.setMaximumSize(QtCore.QSize(121, 31))
        self.motorStatus.setObjectName(_fromUtf8("motorStatus"))
        self.gridLayout.addWidget(self.motorStatus, 2, 1, 1, 1)
        self.gateControl = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gateControl.sizePolicy().hasHeightForWidth())
        self.gateControl.setSizePolicy(sizePolicy)
        self.gateControl.setMaximumSize(QtCore.QSize(121, 31))
        self.gateControl.setObjectName(_fromUtf8("gateControl"))
        self.gridLayout.addWidget(self.gateControl, 4, 1, 1, 1)
        self.batteryVolage = QtGui.QProgressBar(self.centralwidget)
        self.batteryVolage.setMaximumSize(QtCore.QSize(121, 20))
        self.batteryVolage.setProperty("value", 0)
        self.batteryVolage.setObjectName(_fromUtf8("batteryVolage"))
        self.gridLayout.addWidget(self.batteryVolage, 9, 1, 1, 1)
        self.groupBox_14 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.zitaijiaolable_2 = QtGui.QLabel(self.groupBox_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zitaijiaolable_2.sizePolicy().hasHeightForWidth())
        self.zitaijiaolable_2.setSizePolicy(sizePolicy)
        self.zitaijiaolable_2.setObjectName(_fromUtf8("zitaijiaolable_2"))
        self.verticalLayout_13.addWidget(self.zitaijiaolable_2)
        self.gridLayout.addWidget(self.groupBox_14, 0, 4, 1, 1)
        self.boardStatus_3 = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boardStatus_3.sizePolicy().hasHeightForWidth())
        self.boardStatus_3.setSizePolicy(sizePolicy)
        self.boardStatus_3.setMaximumSize(QtCore.QSize(121, 31))
        self.boardStatus_3.setObjectName(_fromUtf8("boardStatus_3"))
        self.gridLayout.addWidget(self.boardStatus_3, 1, 5, 1, 1)
        self.boardStatus_2 = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boardStatus_2.sizePolicy().hasHeightForWidth())
        self.boardStatus_2.setSizePolicy(sizePolicy)
        self.boardStatus_2.setMaximumSize(QtCore.QSize(121, 31))
        self.boardStatus_2.setObjectName(_fromUtf8("boardStatus_2"))
        self.gridLayout.addWidget(self.boardStatus_2, 0, 5, 1, 1)
        self.groupBox_23 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_23.setObjectName(_fromUtf8("groupBox_23"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.groupBox_23)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.zitaijiaolable_3 = QtGui.QLabel(self.groupBox_23)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zitaijiaolable_3.sizePolicy().hasHeightForWidth())
        self.zitaijiaolable_3.setSizePolicy(sizePolicy)
        self.zitaijiaolable_3.setObjectName(_fromUtf8("zitaijiaolable_3"))
        self.verticalLayout_22.addWidget(self.zitaijiaolable_3)
        self.gridLayout.addWidget(self.groupBox_23, 1, 4, 1, 1)
        self.groupBox_25 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_25.setObjectName(_fromUtf8("groupBox_25"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.groupBox_25)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.zitaijiaolable_5 = QtGui.QLabel(self.groupBox_25)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zitaijiaolable_5.sizePolicy().hasHeightForWidth())
        self.zitaijiaolable_5.setSizePolicy(sizePolicy)
        self.zitaijiaolable_5.setObjectName(_fromUtf8("zitaijiaolable_5"))
        self.verticalLayout_24.addWidget(self.zitaijiaolable_5)
        self.gridLayout.addWidget(self.groupBox_25, 0, 6, 1, 1)
        self.boardStatus_5 = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boardStatus_5.sizePolicy().hasHeightForWidth())
        self.boardStatus_5.setSizePolicy(sizePolicy)
        self.boardStatus_5.setMaximumSize(QtCore.QSize(121, 31))
        self.boardStatus_5.setObjectName(_fromUtf8("boardStatus_5"))
        self.gridLayout.addWidget(self.boardStatus_5, 0, 7, 1, 1)
        self.groupBox_18 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_18.setTitle(_fromUtf8(""))
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_18)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_17.addWidget(self.label_18)
        self.gridLayout.addWidget(self.groupBox_18, 3, 2, 1, 1)
        self.groupBox_19 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_19.setTitle(_fromUtf8(""))
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_19)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_18.addWidget(self.label_19)
        self.gridLayout.addWidget(self.groupBox_19, 4, 2, 1, 1)
        self.groupBox_15 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_15.setTitle(_fromUtf8(""))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_15)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_14.addWidget(self.label_15)
        self.gridLayout.addWidget(self.groupBox_15, 5, 2, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_10.setTitle(_fromUtf8(""))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_9.addWidget(self.label_10)
        self.gridLayout.addWidget(self.groupBox_10, 6, 2, 1, 1)
        self.groupBox_12 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_12.setTitle(_fromUtf8(""))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_11.addWidget(self.label_12)
        self.gridLayout.addWidget(self.groupBox_12, 7, 2, 1, 1)
        self.motorleft = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motorleft.sizePolicy().hasHeightForWidth())
        self.motorleft.setSizePolicy(sizePolicy)
        self.motorleft.setNumDigits(5)
        self.motorleft.setDigitCount(5)
        self.motorleft.setMode(QtGui.QLCDNumber.Hex)
        self.motorleft.setProperty("value", 0.0)
        self.motorleft.setProperty("intValue", 0)
        self.motorleft.setObjectName(_fromUtf8("motorleft"))
        self.gridLayout.addWidget(self.motorleft, 8, 3, 1, 1)
        self.motoright = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motoright.sizePolicy().hasHeightForWidth())
        self.motoright.setSizePolicy(sizePolicy)
        self.motoright.setMode(QtGui.QLCDNumber.Hex)
        self.motoright.setObjectName(_fromUtf8("motoright"))
        self.gridLayout.addWidget(self.motoright, 9, 3, 1, 1)
        self.motorspeedl = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motorspeedl.sizePolicy().hasHeightForWidth())
        self.motorspeedl.setSizePolicy(sizePolicy)
        self.motorspeedl.setProperty("intValue", 0)
        self.motorspeedl.setObjectName(_fromUtf8("motorspeedl"))
        self.gridLayout.addWidget(self.motorspeedl, 6, 3, 1, 1)
        self.motorspeedr = QtGui.QLCDNumber(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motorspeedr.sizePolicy().hasHeightForWidth())
        self.motorspeedr.setSizePolicy(sizePolicy)
        self.motorspeedr.setObjectName(_fromUtf8("motorspeedr"))
        self.gridLayout.addWidget(self.motorspeedr, 7, 3, 1, 1)
        self.sanzhoujiasudu = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sanzhoujiasudu.sizePolicy().hasHeightForWidth())
        self.sanzhoujiasudu.setSizePolicy(sizePolicy)
        self.sanzhoujiasudu.setMaximumSize(QtCore.QSize(121, 31))
        self.sanzhoujiasudu.setObjectName(_fromUtf8("sanzhoujiasudu"))
        self.gridLayout.addWidget(self.sanzhoujiasudu, 4, 3, 1, 1)
        self.siluspeed = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.siluspeed.sizePolicy().hasHeightForWidth())
        self.siluspeed.setSizePolicy(sizePolicy)
        self.siluspeed.setMaximumSize(QtCore.QSize(121, 31))
        self.siluspeed.setObjectName(_fromUtf8("siluspeed"))
        self.gridLayout.addWidget(self.siluspeed, 5, 3, 1, 1)
        self.zhongliang = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zhongliang.sizePolicy().hasHeightForWidth())
        self.zhongliang.setSizePolicy(sizePolicy)
        self.zhongliang.setMaximumSize(QtCore.QSize(121, 31))
        self.zhongliang.setObjectName(_fromUtf8("zhongliang"))
        self.gridLayout.addWidget(self.zhongliang, 3, 3, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.textBrowser = QtGui.QTextBrowser(self.groupBox)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.horizontalLayout.addWidget(self.textBrowser)
        self.gridLayout.addWidget(self.groupBox, 2, 4, 7, 4)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1046, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.manual = QtGui.QMenu(self.menubar)
        self.manual.setObjectName(_fromUtf8("manual"))
        self.protomenu = QtGui.QMenu(self.menubar)
        self.protomenu.setObjectName(_fromUtf8("protomenu"))
        self.toolmenu = QtGui.QMenu(self.menubar)
        self.toolmenu.setObjectName(_fromUtf8("toolmenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.manual.menuAction())
        self.menubar.addAction(self.protomenu.menuAction())
        self.menubar.addAction(self.toolmenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "yogoTest2.2.0", None))
        self.boardStatus_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0%</p></body></html>", None))
        self.groupBox_24.setTitle(_translate("MainWindow", "B->C", None))
        self.zitaijiaolable_4.setText(_translate("MainWindow", "  误码率：", None))
        self.motorStatuslable.setText(_translate("MainWindow", "电机状态：", None))
        self.label_17.setText(_translate("MainWindow", "  电梯门开关：", None))
        self.label_9.setText(_translate("MainWindow", "右电机编码值：", None))
        self.label_7.setText(_translate("MainWindow", "左电机编码值：", None))
        self.catchDelable.setText(_translate("MainWindow", "碰撞检测：", None))
        self.sanzhoulable.setText(_translate("MainWindow", "    三轴磁场：", None))
        self.label_20.setText(_translate("MainWindow", "    限位开关：", None))
        self.insideGatelable.setText(_translate("MainWindow", "内门状态：", None))
        self.zitaijiaolable.setText(_translate("MainWindow", "  姿态角：", None))
        self.label_22.setText(_translate("MainWindow", "头顶触摸：", None))
        self.boardlable.setText(_translate("MainWindow", " 单板状态：", None))
        self.gateControlable.setText(_translate("MainWindow", "门控状态：", None))
        self.label_4.setText(_translate("MainWindow", "充电状态：", None))
        self.downDeltelable.setText(_translate("MainWindow", "倾倒检测：", None))
        self.label_5.setText(_translate("MainWindow", "     SOC：", None))
        self.groupBox_14.setTitle(_translate("MainWindow", "C->B", None))
        self.zitaijiaolable_2.setText(_translate("MainWindow", "  丢包率：", None))
        self.boardStatus_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0%</p></body></html>", None))
        self.boardStatus_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0%</p></body></html>", None))
        self.groupBox_23.setTitle(_translate("MainWindow", "C->B", None))
        self.zitaijiaolable_3.setText(_translate("MainWindow", "  误码率：", None))
        self.groupBox_25.setTitle(_translate("MainWindow", "B->C", None))
        self.zitaijiaolable_5.setText(_translate("MainWindow", "  丢包率：", None))
        self.boardStatus_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0%</p></body></html>", None))
        self.label_18.setText(_translate("MainWindow", "  舱内称重值：", None))
        self.label_19.setText(_translate("MainWindow", "  三轴加速度：", None))
        self.label_15.setText(_translate("MainWindow", "  四路超声值：", None))
        self.label_10.setText(_translate("MainWindow", "  左电机速度：", None))
        self.label_12.setText(_translate("MainWindow", "  右电机速度：", None))
        self.menu.setTitle(_translate("MainWindow", "连接设置", None))
        self.manual.setTitle(_translate("MainWindow", "配置", None))
        self.protomenu.setTitle(_translate("MainWindow", "协议测试", None))
        self.toolmenu.setTitle(_translate("MainWindow", "工具", None))

import image_rc
