# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xtboard.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Xt_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(567, 444)
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 41, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(60, 11, 81, 31))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 541, 381))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.downlightoff = QtGui.QPushButton(self.groupBox)
        self.downlightoff.setEnabled(False)
        self.downlightoff.setCheckable(True)
        self.downlightoff.setObjectName(_fromUtf8("downlightoff"))
        self.gridLayout.addWidget(self.downlightoff, 3, 3, 1, 1)
        self.downswitch = QtGui.QLabel(self.groupBox)
        self.downswitch.setObjectName(_fromUtf8("downswitch"))
        self.gridLayout.addWidget(self.downswitch, 5, 3, 1, 1)
        self.downwei = QtGui.QLabel(self.groupBox)
        self.downwei.setObjectName(_fromUtf8("downwei"))
        self.gridLayout.addWidget(self.downwei, 6, 3, 1, 1)
        self.uplock = QtGui.QPushButton(self.groupBox)
        self.uplock.setEnabled(False)
        self.uplock.setCheckable(True)
        self.uplock.setChecked(True)
        self.uplock.setObjectName(_fromUtf8("uplock"))
        self.gridLayout.addWidget(self.uplock, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.downlock = QtGui.QPushButton(self.groupBox)
        self.downlock.setEnabled(False)
        self.downlock.setCheckable(True)
        self.downlock.setChecked(True)
        self.downlock.setObjectName(_fromUtf8("downlock"))
        self.gridLayout.addWidget(self.downlock, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.downunlock = QtGui.QPushButton(self.groupBox)
        self.downunlock.setEnabled(False)
        self.downunlock.setCheckable(True)
        self.downunlock.setObjectName(_fromUtf8("downunlock"))
        self.gridLayout.addWidget(self.downunlock, 1, 3, 1, 1)
        self.upunlock = QtGui.QPushButton(self.groupBox)
        self.upunlock.setEnabled(False)
        self.upunlock.setCheckable(True)
        self.upunlock.setObjectName(_fromUtf8("upunlock"))
        self.gridLayout.addWidget(self.upunlock, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.upswitch = QtGui.QLabel(self.groupBox)
        self.upswitch.setObjectName(_fromUtf8("upswitch"))
        self.gridLayout.addWidget(self.upswitch, 5, 1, 1, 1)
        self.downlighton = QtGui.QPushButton(self.groupBox)
        self.downlighton.setEnabled(False)
        self.downlighton.setCheckable(True)
        self.downlighton.setChecked(True)
        self.downlighton.setObjectName(_fromUtf8("downlighton"))
        self.gridLayout.addWidget(self.downlighton, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 6, 0, 1, 1)
        self.uplighton = QtGui.QPushButton(self.groupBox)
        self.uplighton.setEnabled(False)
        self.uplighton.setCheckable(True)
        self.uplighton.setChecked(True)
        self.uplighton.setObjectName(_fromUtf8("uplighton"))
        self.gridLayout.addWidget(self.uplighton, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 5, 2, 1, 1)
        self.upwei = QtGui.QLabel(self.groupBox)
        self.upwei.setObjectName(_fromUtf8("upwei"))
        self.gridLayout.addWidget(self.upwei, 6, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 8, 0, 1, 1)
        self.start = QtGui.QPushButton(self.groupBox)
        self.start.setStyleSheet(_fromUtf8("background-color: rgb(85, 255, 0);"))
        self.start.setObjectName(_fromUtf8("start"))
        self.gridLayout.addWidget(self.start, 8, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 6, 2, 1, 1)
        self.uplightoff = QtGui.QPushButton(self.groupBox)
        self.uplightoff.setEnabled(False)
        self.uplightoff.setCheckable(True)
        self.uplightoff.setObjectName(_fromUtf8("uplightoff"))
        self.gridLayout.addWidget(self.uplightoff, 2, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.warr = QtGui.QLabel(self.groupBox)
        self.warr.setText(_fromUtf8(""))
        self.warr.setObjectName(_fromUtf8("warr"))
        self.gridLayout.addWidget(self.warr, 4, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 4, 2, 1, 1)
        self.err = QtGui.QLabel(self.groupBox)
        self.err.setText(_fromUtf8(""))
        self.err.setObjectName(_fromUtf8("err"))
        self.gridLayout.addWidget(self.err, 4, 3, 1, 1)
        self.pause = QtGui.QPushButton(self.groupBox)
        self.pause.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.pause.setObjectName(_fromUtf8("pause"))
        self.gridLayout.addWidget(self.pause, 8, 3, 1, 1)
        self.manual = QtGui.QPushButton(Dialog)
        self.manual.setGeometry(QtCore.QRect(310, 10, 71, 31))
        self.manual.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.manual.setCheckable(False)
        self.manual.setChecked(False)
        self.manual.setObjectName(_fromUtf8("manual"))
        self.manpause = QtGui.QPushButton(Dialog)
        self.manpause.setGeometry(QtCore.QRect(470, 10, 81, 31))
        self.manpause.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 127);"))
        self.manpause.setObjectName(_fromUtf8("manpause"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "箱体板测试", None))
        self.label.setText(_translate("Dialog", "模式：", None))
        self.comboBox.setItemText(0, _translate("Dialog", "单测", None))
        self.comboBox.setItemText(1, _translate("Dialog", "联测", None))
        self.downlightoff.setText(_translate("Dialog", "关灯", None))
        self.downswitch.setText(_translate("Dialog", "到位", None))
        self.downwei.setText(_translate("Dialog", "0", None))
        self.uplock.setText(_translate("Dialog", "上锁", None))
        self.label_3.setText(_translate("Dialog", "下舵机", None))
        self.downlock.setText(_translate("Dialog", "上锁", None))
        self.label_4.setText(_translate("Dialog", "上侧灯", None))
        self.label_2.setText(_translate("Dialog", "上舵机", None))
        self.downunlock.setText(_translate("Dialog", "解锁", None))
        self.upunlock.setText(_translate("Dialog", "解锁", None))
        self.label_6.setText(_translate("Dialog", "上限位", None))
        self.upswitch.setText(_translate("Dialog", "到位", None))
        self.downlighton.setText(_translate("Dialog", "开灯", None))
        self.label_5.setText(_translate("Dialog", "下侧灯", None))
        self.label_13.setText(_translate("Dialog", "上称重", None))
        self.uplighton.setText(_translate("Dialog", "开灯", None))
        self.label_10.setText(_translate("Dialog", "下限位", None))
        self.upwei.setText(_translate("Dialog", "0", None))
        self.label_16.setText(_translate("Dialog", "自动测试", None))
        self.start.setText(_translate("Dialog", "开始", None))
        self.label_14.setText(_translate("Dialog", "下称重", None))
        self.uplightoff.setText(_translate("Dialog", "关灯", None))
        self.label_7.setText(_translate("Dialog", "警告码：", None))
        self.label_9.setText(_translate("Dialog", "错误码：", None))
        self.pause.setText(_translate("Dialog", "暂停", None))
        self.manual.setText(_translate("Dialog", "调试模式", None))
        self.manpause.setText(_translate("Dialog", "暂停", None))

